// Generated by CIRCT firtool-1.62.0
module MD_EX1_EX2_Reg(
  input         clock,
                reset,
                io_flush,
                io_stall,
                io_inst_pack_EX1_rd_valid,
  input  [5:0]  io_inst_pack_EX1_prd,
  input  [4:0]  io_inst_pack_EX1_rob_index,
  input  [9:0]  io_inst_pack_EX1_priv_vec,
  input  [3:0]  io_inst_pack_EX1_alu_op,
  input         io_inst_pack_EX1_inst_valid,
  input  [31:0] io_csr_wdata_EX1,
                io_csr_rdata_EX1,
  output        io_inst_pack_EX2_rd_valid,
  output [5:0]  io_inst_pack_EX2_prd,
  output [4:0]  io_inst_pack_EX2_rob_index,
  output [9:0]  io_inst_pack_EX2_priv_vec,
  output [3:0]  io_inst_pack_EX2_alu_op,
  output        io_inst_pack_EX2_inst_valid,
  output [31:0] io_csr_wdata_EX2,
                io_csr_rdata_EX2
);

  reg         inst_pack_reg_rd_valid;
  reg  [5:0]  inst_pack_reg_prd;
  reg  [4:0]  inst_pack_reg_rob_index;
  reg  [9:0]  inst_pack_reg_priv_vec;
  reg  [3:0]  inst_pack_reg_alu_op;
  reg         inst_pack_reg_inst_valid;
  reg  [31:0] csr_wdata_reg;
  reg  [31:0] csr_rdata_reg;
  wire        _GEN = io_stall ? inst_pack_reg_rd_valid : io_inst_pack_EX1_rd_valid;
  wire        _GEN_0 = io_stall ? inst_pack_reg_inst_valid : io_inst_pack_EX1_inst_valid;
  always @(posedge clock) begin
    if (reset) begin
      inst_pack_reg_rd_valid <= 1'h0;
      inst_pack_reg_prd <= 6'h0;
      inst_pack_reg_rob_index <= 5'h0;
      inst_pack_reg_priv_vec <= 10'h0;
      inst_pack_reg_alu_op <= 4'h0;
      inst_pack_reg_inst_valid <= 1'h0;
      csr_wdata_reg <= 32'h0;
      csr_rdata_reg <= 32'h0;
    end
    else begin
      inst_pack_reg_rd_valid <= ~io_flush & _GEN;
      if (io_flush) begin
        inst_pack_reg_prd <= 6'h0;
        inst_pack_reg_rob_index <= 5'h0;
        inst_pack_reg_priv_vec <= 10'h0;
        inst_pack_reg_alu_op <= 4'h0;
      end
      else if (io_stall) begin
      end
      else begin
        inst_pack_reg_prd <= io_inst_pack_EX1_prd;
        inst_pack_reg_rob_index <= io_inst_pack_EX1_rob_index;
        inst_pack_reg_priv_vec <= io_inst_pack_EX1_priv_vec;
        inst_pack_reg_alu_op <= io_inst_pack_EX1_alu_op;
      end
      inst_pack_reg_inst_valid <= ~io_flush & _GEN_0;
      if (io_flush | io_stall) begin
      end
      else begin
        csr_wdata_reg <= io_csr_wdata_EX1;
        csr_rdata_reg <= io_csr_rdata_EX1;
      end
    end
  end // always @(posedge)
  assign io_inst_pack_EX2_rd_valid = inst_pack_reg_rd_valid;
  assign io_inst_pack_EX2_prd = inst_pack_reg_prd;
  assign io_inst_pack_EX2_rob_index = inst_pack_reg_rob_index;
  assign io_inst_pack_EX2_priv_vec = inst_pack_reg_priv_vec;
  assign io_inst_pack_EX2_alu_op = inst_pack_reg_alu_op;
  assign io_inst_pack_EX2_inst_valid = inst_pack_reg_inst_valid;
  assign io_csr_wdata_EX2 = csr_wdata_reg;
  assign io_csr_rdata_EX2 = csr_rdata_reg;
endmodule

