// Generated by CIRCT firtool-1.62.0
module Exception_LS(
  input  [31:0] io_addr_EX,
  input  [4:0]  io_mem_type_EX,
  output [7:0]  io_exception_ls
);

  assign io_exception_ls =
    (|(io_addr_EX[6:0] & 7'((7'h1 << io_mem_type_EX[1:0]) - 7'h1))) ? 8'h89 : 8'h0;
endmodule

