// Generated by CIRCT firtool-1.62.0
module IS_RF_Reg_2(
  input         clock,
                reset,
                io_flush,
                io_stall,
  input  [5:0]  io_inst_pack_IS_prj,
                io_inst_pack_IS_prk,
  input         io_inst_pack_IS_rd_valid,
  input  [5:0]  io_inst_pack_IS_prd,
  input  [31:0] io_inst_pack_IS_imm,
  input  [4:0]  io_inst_pack_IS_rob_index,
  input  [9:0]  io_inst_pack_IS_priv_vec,
  input  [3:0]  io_inst_pack_IS_alu_op,
  input         io_inst_pack_IS_inst_valid,
  output [5:0]  io_inst_pack_RF_prj,
                io_inst_pack_RF_prk,
  output        io_inst_pack_RF_rd_valid,
  output [5:0]  io_inst_pack_RF_prd,
  output [31:0] io_inst_pack_RF_imm,
  output [4:0]  io_inst_pack_RF_rob_index,
  output [9:0]  io_inst_pack_RF_priv_vec,
  output [3:0]  io_inst_pack_RF_alu_op,
  output        io_inst_pack_RF_inst_valid
);

  reg  [5:0]  inst_pack_reg_prj;
  reg  [5:0]  inst_pack_reg_prk;
  reg         inst_pack_reg_rd_valid;
  reg  [5:0]  inst_pack_reg_prd;
  reg  [31:0] inst_pack_reg_imm;
  reg  [4:0]  inst_pack_reg_rob_index;
  reg  [9:0]  inst_pack_reg_priv_vec;
  reg  [3:0]  inst_pack_reg_alu_op;
  reg         inst_pack_reg_inst_valid;
  wire        _GEN = io_stall ? inst_pack_reg_rd_valid : io_inst_pack_IS_rd_valid;
  wire        _GEN_0 = io_stall ? inst_pack_reg_inst_valid : io_inst_pack_IS_inst_valid;
  always @(posedge clock) begin
    if (reset) begin
      inst_pack_reg_prj <= 6'h0;
      inst_pack_reg_prk <= 6'h0;
      inst_pack_reg_rd_valid <= 1'h0;
      inst_pack_reg_prd <= 6'h0;
      inst_pack_reg_imm <= 32'h0;
      inst_pack_reg_rob_index <= 5'h0;
      inst_pack_reg_priv_vec <= 10'h0;
      inst_pack_reg_alu_op <= 4'h0;
      inst_pack_reg_inst_valid <= 1'h0;
    end
    else begin
      if (io_flush) begin
        inst_pack_reg_prj <= 6'h0;
        inst_pack_reg_prk <= 6'h0;
        inst_pack_reg_prd <= 6'h0;
        inst_pack_reg_imm <= 32'h0;
        inst_pack_reg_rob_index <= 5'h0;
        inst_pack_reg_priv_vec <= 10'h0;
        inst_pack_reg_alu_op <= 4'h0;
      end
      else if (io_stall) begin
      end
      else begin
        inst_pack_reg_prj <= io_inst_pack_IS_prj;
        inst_pack_reg_prk <= io_inst_pack_IS_prk;
        inst_pack_reg_prd <= io_inst_pack_IS_prd;
        inst_pack_reg_imm <= io_inst_pack_IS_imm;
        inst_pack_reg_rob_index <= io_inst_pack_IS_rob_index;
        inst_pack_reg_priv_vec <= io_inst_pack_IS_priv_vec;
        inst_pack_reg_alu_op <= io_inst_pack_IS_alu_op;
      end
      inst_pack_reg_rd_valid <= ~io_flush & _GEN;
      inst_pack_reg_inst_valid <= ~io_flush & _GEN_0;
    end
  end // always @(posedge)
  assign io_inst_pack_RF_prj = inst_pack_reg_prj;
  assign io_inst_pack_RF_prk = inst_pack_reg_prk;
  assign io_inst_pack_RF_rd_valid = inst_pack_reg_rd_valid;
  assign io_inst_pack_RF_prd = inst_pack_reg_prd;
  assign io_inst_pack_RF_imm = inst_pack_reg_imm;
  assign io_inst_pack_RF_rob_index = inst_pack_reg_rob_index;
  assign io_inst_pack_RF_priv_vec = inst_pack_reg_priv_vec;
  assign io_inst_pack_RF_alu_op = inst_pack_reg_alu_op;
  assign io_inst_pack_RF_inst_valid = inst_pack_reg_inst_valid;
endmodule

