// Generated by CIRCT firtool-1.62.0
module Unorder_Issue_Queue(
  input         clock,
                reset,
                io_insts_disp_valid_0,
                io_insts_disp_valid_1,
  input  [5:0]  io_insts_dispatch_0_prj,
                io_insts_dispatch_0_prk,
  input         io_insts_dispatch_0_rd_valid,
  input  [5:0]  io_insts_dispatch_0_prd,
  input  [31:0] io_insts_dispatch_0_imm,
  input  [4:0]  io_insts_dispatch_0_rob_index,
  input  [3:0]  io_insts_dispatch_0_alu_op,
  input         io_insts_dispatch_0_alu_rs1_sel,
  input  [1:0]  io_insts_dispatch_0_alu_rs2_sel,
  input  [31:0] io_insts_dispatch_0_pc,
  input  [5:0]  io_insts_dispatch_1_prj,
                io_insts_dispatch_1_prk,
  input         io_insts_dispatch_1_rd_valid,
  input  [5:0]  io_insts_dispatch_1_prd,
  input  [31:0] io_insts_dispatch_1_imm,
  input  [4:0]  io_insts_dispatch_1_rob_index,
  input  [3:0]  io_insts_dispatch_1_alu_op,
  input         io_insts_dispatch_1_alu_rs1_sel,
  input  [1:0]  io_insts_dispatch_1_alu_rs2_sel,
  input  [31:0] io_insts_dispatch_1_pc,
  input         io_prj_ready_0,
                io_prj_ready_1,
                io_prk_ready_0,
                io_prk_ready_1,
  input  [5:0]  io_wake_preg_0,
                io_wake_preg_1,
                io_wake_preg_2,
                io_wake_preg_3,
                io_ld_mem_prd,
  input         io_issue_ack_0,
                io_issue_ack_1,
                io_issue_ack_2,
                io_issue_ack_3,
                io_issue_ack_4,
                io_issue_ack_5,
  output [5:0]  io_insts_issue_0_inst_prj,
                io_insts_issue_0_inst_prk,
  output        io_insts_issue_0_inst_rd_valid,
  output [5:0]  io_insts_issue_0_inst_prd,
  output [31:0] io_insts_issue_0_inst_imm,
  output [4:0]  io_insts_issue_0_inst_rob_index,
  output [3:0]  io_insts_issue_0_inst_alu_op,
  output        io_insts_issue_0_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_0_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_0_inst_pc,
  output [5:0]  io_insts_issue_1_inst_prj,
                io_insts_issue_1_inst_prk,
  output        io_insts_issue_1_inst_rd_valid,
  output [5:0]  io_insts_issue_1_inst_prd,
  output [31:0] io_insts_issue_1_inst_imm,
  output [4:0]  io_insts_issue_1_inst_rob_index,
  output [3:0]  io_insts_issue_1_inst_alu_op,
  output        io_insts_issue_1_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_1_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_1_inst_pc,
  output [5:0]  io_insts_issue_2_inst_prj,
                io_insts_issue_2_inst_prk,
  output        io_insts_issue_2_inst_rd_valid,
  output [5:0]  io_insts_issue_2_inst_prd,
  output [31:0] io_insts_issue_2_inst_imm,
  output [4:0]  io_insts_issue_2_inst_rob_index,
  output [3:0]  io_insts_issue_2_inst_alu_op,
  output        io_insts_issue_2_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_2_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_2_inst_pc,
  output [5:0]  io_insts_issue_3_inst_prj,
                io_insts_issue_3_inst_prk,
  output        io_insts_issue_3_inst_rd_valid,
  output [5:0]  io_insts_issue_3_inst_prd,
  output [31:0] io_insts_issue_3_inst_imm,
  output [4:0]  io_insts_issue_3_inst_rob_index,
  output [3:0]  io_insts_issue_3_inst_alu_op,
  output        io_insts_issue_3_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_3_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_3_inst_pc,
  output [5:0]  io_insts_issue_4_inst_prj,
                io_insts_issue_4_inst_prk,
  output        io_insts_issue_4_inst_rd_valid,
  output [5:0]  io_insts_issue_4_inst_prd,
  output [31:0] io_insts_issue_4_inst_imm,
  output [4:0]  io_insts_issue_4_inst_rob_index,
  output [3:0]  io_insts_issue_4_inst_alu_op,
  output        io_insts_issue_4_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_4_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_4_inst_pc,
  output [5:0]  io_insts_issue_5_inst_prj,
                io_insts_issue_5_inst_prk,
  output        io_insts_issue_5_inst_rd_valid,
  output [5:0]  io_insts_issue_5_inst_prd,
  output [31:0] io_insts_issue_5_inst_imm,
  output [4:0]  io_insts_issue_5_inst_rob_index,
  output [3:0]  io_insts_issue_5_inst_alu_op,
  output        io_insts_issue_5_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_5_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_5_inst_pc,
  output        io_issue_req_0,
                io_issue_req_1,
                io_issue_req_2,
                io_issue_req_3,
                io_issue_req_4,
                io_issue_req_5,
  output [3:0]  io_elem_num,
  output        io_full,
  input         io_stall,
                io_flush,
                io_dcache_miss
);

  reg  [5:0]  queue_0_inst_prj;
  reg  [5:0]  queue_0_inst_prk;
  reg         queue_0_inst_rd_valid;
  reg  [5:0]  queue_0_inst_prd;
  reg  [31:0] queue_0_inst_imm;
  reg  [4:0]  queue_0_inst_rob_index;
  reg  [3:0]  queue_0_inst_alu_op;
  reg         queue_0_inst_alu_rs1_sel;
  reg  [1:0]  queue_0_inst_alu_rs2_sel;
  reg  [31:0] queue_0_inst_pc;
  reg         queue_0_prj_waked;
  reg         queue_0_prk_waked;
  reg         queue_0_prj_wake_by_ld;
  reg         queue_0_prk_wake_by_ld;
  reg  [5:0]  queue_1_inst_prj;
  reg  [5:0]  queue_1_inst_prk;
  reg         queue_1_inst_rd_valid;
  reg  [5:0]  queue_1_inst_prd;
  reg  [31:0] queue_1_inst_imm;
  reg  [4:0]  queue_1_inst_rob_index;
  reg  [3:0]  queue_1_inst_alu_op;
  reg         queue_1_inst_alu_rs1_sel;
  reg  [1:0]  queue_1_inst_alu_rs2_sel;
  reg  [31:0] queue_1_inst_pc;
  reg         queue_1_prj_waked;
  reg         queue_1_prk_waked;
  reg         queue_1_prj_wake_by_ld;
  reg         queue_1_prk_wake_by_ld;
  reg  [5:0]  queue_2_inst_prj;
  reg  [5:0]  queue_2_inst_prk;
  reg         queue_2_inst_rd_valid;
  reg  [5:0]  queue_2_inst_prd;
  reg  [31:0] queue_2_inst_imm;
  reg  [4:0]  queue_2_inst_rob_index;
  reg  [3:0]  queue_2_inst_alu_op;
  reg         queue_2_inst_alu_rs1_sel;
  reg  [1:0]  queue_2_inst_alu_rs2_sel;
  reg  [31:0] queue_2_inst_pc;
  reg         queue_2_prj_waked;
  reg         queue_2_prk_waked;
  reg         queue_2_prj_wake_by_ld;
  reg         queue_2_prk_wake_by_ld;
  reg  [5:0]  queue_3_inst_prj;
  reg  [5:0]  queue_3_inst_prk;
  reg         queue_3_inst_rd_valid;
  reg  [5:0]  queue_3_inst_prd;
  reg  [31:0] queue_3_inst_imm;
  reg  [4:0]  queue_3_inst_rob_index;
  reg  [3:0]  queue_3_inst_alu_op;
  reg         queue_3_inst_alu_rs1_sel;
  reg  [1:0]  queue_3_inst_alu_rs2_sel;
  reg  [31:0] queue_3_inst_pc;
  reg         queue_3_prj_waked;
  reg         queue_3_prk_waked;
  reg         queue_3_prj_wake_by_ld;
  reg         queue_3_prk_wake_by_ld;
  reg  [5:0]  queue_4_inst_prj;
  reg  [5:0]  queue_4_inst_prk;
  reg         queue_4_inst_rd_valid;
  reg  [5:0]  queue_4_inst_prd;
  reg  [31:0] queue_4_inst_imm;
  reg  [4:0]  queue_4_inst_rob_index;
  reg  [3:0]  queue_4_inst_alu_op;
  reg         queue_4_inst_alu_rs1_sel;
  reg  [1:0]  queue_4_inst_alu_rs2_sel;
  reg  [31:0] queue_4_inst_pc;
  reg         queue_4_prj_waked;
  reg         queue_4_prk_waked;
  reg         queue_4_prj_wake_by_ld;
  reg         queue_4_prk_wake_by_ld;
  reg  [5:0]  queue_5_inst_prj;
  reg  [5:0]  queue_5_inst_prk;
  reg         queue_5_inst_rd_valid;
  reg  [5:0]  queue_5_inst_prd;
  reg  [31:0] queue_5_inst_imm;
  reg  [4:0]  queue_5_inst_rob_index;
  reg  [3:0]  queue_5_inst_alu_op;
  reg         queue_5_inst_alu_rs1_sel;
  reg  [1:0]  queue_5_inst_alu_rs2_sel;
  reg  [31:0] queue_5_inst_pc;
  reg         queue_5_prj_waked;
  reg         queue_5_prk_waked;
  reg         queue_5_prj_wake_by_ld;
  reg         queue_5_prk_wake_by_ld;
  reg  [3:0]  num;
  reg  [5:0]  qvalid;
  wire [1:0]  ins_num = 2'({1'h0, io_insts_disp_valid_0} + {1'h0, io_insts_disp_valid_1});
  wire [3:0]  _num_pop_T_2 =
    4'(num
       - {3'h0,
          |{io_issue_ack_5,
            io_issue_ack_4,
            io_issue_ack_3,
            io_issue_ack_2,
            io_issue_ack_1,
            io_issue_ack_0}});
  wire [5:0]  _qvalid_pop_T =
    {io_issue_ack_5,
     io_issue_ack_4,
     io_issue_ack_3,
     io_issue_ack_2,
     io_issue_ack_1,
     io_issue_ack_0};
  wire [5:0]  _qvalid_pop_T_3 = {1'h0, qvalid[5:1]};
  wire [5:0]  qvalid_pop = (|_qvalid_pop_T) ? _qvalid_pop_T_3 : qvalid;
  wire [4:0]  issue =
    ~(5'({io_issue_ack_4, io_issue_ack_3, io_issue_ack_2, io_issue_ack_1, io_issue_ack_0}
         - 5'h1));
  wire        index = 1'(1'h0 - _num_pop_T_2[0]);
  wire        _GEN = ~io_insts_disp_valid_0 & io_insts_disp_valid_1;
  wire        _GEN_0 = _GEN | index;
  wire [5:0]  _GEN_1 = _GEN_0 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_1_inst_prj = issue[0] ? queue_1_inst_prj : queue_0_inst_prj;
  wire [5:0]  queue_next_inst_prj = qvalid_pop[0] ? _queue_next_T_1_inst_prj : _GEN_1;
  wire [5:0]  _GEN_2 = _GEN_0 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_1_inst_prk = issue[0] ? queue_1_inst_prk : queue_0_inst_prk;
  wire [5:0]  queue_next_inst_prk = qvalid_pop[0] ? _queue_next_T_1_inst_prk : _GEN_2;
  wire [5:0]  _queue_0_prj_wake_by_ld_T = queue_next_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_0_prk_wake_by_ld_T = queue_next_inst_prk ^ io_wake_preg_3;
  wire        _index_T_2 = 1'(1'h1 - _num_pop_T_2[0]);
  wire        _GEN_3 = _GEN | _index_T_2;
  wire [5:0]  _GEN_4 = _GEN_3 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_3_inst_prj = issue[1] ? queue_2_inst_prj : queue_1_inst_prj;
  wire [5:0]  queue_next_1_inst_prj = qvalid_pop[1] ? _queue_next_T_3_inst_prj : _GEN_4;
  wire [5:0]  _GEN_5 = _GEN_3 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_3_inst_prk = issue[1] ? queue_2_inst_prk : queue_1_inst_prk;
  wire [5:0]  queue_next_1_inst_prk = qvalid_pop[1] ? _queue_next_T_3_inst_prk : _GEN_5;
  wire [5:0]  _queue_1_prj_wake_by_ld_T = queue_next_1_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_1_prk_wake_by_ld_T = queue_next_1_inst_prk ^ io_wake_preg_3;
  wire        _index_T_4 = 1'(1'h0 - _num_pop_T_2[0]);
  wire        _GEN_6 = _GEN | _index_T_4;
  wire [5:0]  _GEN_7 = _GEN_6 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_5_inst_prj = issue[2] ? queue_3_inst_prj : queue_2_inst_prj;
  wire [5:0]  queue_next_2_inst_prj = qvalid_pop[2] ? _queue_next_T_5_inst_prj : _GEN_7;
  wire [5:0]  _GEN_8 = _GEN_6 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_5_inst_prk = issue[2] ? queue_3_inst_prk : queue_2_inst_prk;
  wire [5:0]  queue_next_2_inst_prk = qvalid_pop[2] ? _queue_next_T_5_inst_prk : _GEN_8;
  wire [5:0]  _queue_2_prj_wake_by_ld_T = queue_next_2_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_2_prk_wake_by_ld_T = queue_next_2_inst_prk ^ io_wake_preg_3;
  wire        _index_T_6 = 1'(1'h1 - _num_pop_T_2[0]);
  wire        _GEN_9 = _GEN | _index_T_6;
  wire [5:0]  _GEN_10 = _GEN_9 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_7_inst_prj = issue[3] ? queue_4_inst_prj : queue_3_inst_prj;
  wire [5:0]  queue_next_3_inst_prj = qvalid_pop[3] ? _queue_next_T_7_inst_prj : _GEN_10;
  wire [5:0]  _GEN_11 = _GEN_9 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_7_inst_prk = issue[3] ? queue_4_inst_prk : queue_3_inst_prk;
  wire [5:0]  queue_next_3_inst_prk = qvalid_pop[3] ? _queue_next_T_7_inst_prk : _GEN_11;
  wire [5:0]  _queue_3_prj_wake_by_ld_T = queue_next_3_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_3_prk_wake_by_ld_T = queue_next_3_inst_prk ^ io_wake_preg_3;
  wire        _index_T_8 = 1'(1'h0 - _num_pop_T_2[0]);
  wire        _GEN_12 = _GEN | _index_T_8;
  wire [5:0]  _GEN_13 = _GEN_12 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_9_inst_prj = issue[4] ? queue_5_inst_prj : queue_4_inst_prj;
  wire [5:0]  queue_next_4_inst_prj = qvalid_pop[4] ? _queue_next_T_9_inst_prj : _GEN_13;
  wire [5:0]  _GEN_14 = _GEN_12 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_9_inst_prk = issue[4] ? queue_5_inst_prk : queue_4_inst_prk;
  wire [5:0]  queue_next_4_inst_prk = qvalid_pop[4] ? _queue_next_T_9_inst_prk : _GEN_14;
  wire [5:0]  _queue_4_prj_wake_by_ld_T = queue_next_4_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_4_prk_wake_by_ld_T = queue_next_4_inst_prk ^ io_wake_preg_3;
  wire        _index_T_10 = 1'(1'h1 - _num_pop_T_2[0]);
  wire        _GEN_15 = _GEN | _index_T_10;
  wire [5:0]  _GEN_16 = _GEN_15 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  queue_next_5_inst_prj = qvalid_pop[5] ? queue_5_inst_prj : _GEN_16;
  wire [5:0]  _GEN_17 = _GEN_15 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  queue_next_5_inst_prk = qvalid_pop[5] ? queue_5_inst_prk : _GEN_17;
  wire [5:0]  _queue_5_prj_wake_by_ld_T = queue_next_5_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_5_prk_wake_by_ld_T = queue_next_5_inst_prk ^ io_wake_preg_3;
  wire        _GEN_18 = _GEN_0 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_1_prj_waked =
    issue[0] ? queue_1_prj_waked : queue_0_prj_waked;
  wire        queue_next_prj_waked = qvalid_pop[0] ? _queue_next_T_1_prj_waked : _GEN_18;
  wire        _GEN_19 = _GEN_0 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_1_prk_waked =
    issue[0] ? queue_1_prk_waked : queue_0_prk_waked;
  wire        queue_next_prk_waked = qvalid_pop[0] ? _queue_next_T_1_prk_waked : _GEN_19;
  wire [5:0]  _GEN_20 = index ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire        _GEN_21 =
    _GEN
      ? (io_insts_dispatch_1_prj ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_20 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_1_prj_wake_by_ld =
    issue[0] ? queue_1_prj_wake_by_ld : queue_0_prj_wake_by_ld;
  wire        queue_next_prj_wake_by_ld =
    qvalid_pop[0] ? _queue_next_T_1_prj_wake_by_ld : _GEN_21;
  wire [5:0]  _GEN_22 = index ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire        _GEN_23 =
    _GEN
      ? (io_insts_dispatch_1_prk ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_22 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_1_prk_wake_by_ld =
    issue[0] ? queue_1_prk_wake_by_ld : queue_0_prk_wake_by_ld;
  wire        queue_next_prk_wake_by_ld =
    qvalid_pop[0] ? _queue_next_T_1_prk_wake_by_ld : _GEN_23;
  wire        _GEN_24 = _GEN_3 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_3_prj_waked =
    issue[1] ? queue_2_prj_waked : queue_1_prj_waked;
  wire        queue_next_1_prj_waked =
    qvalid_pop[1] ? _queue_next_T_3_prj_waked : _GEN_24;
  wire        _GEN_25 = _GEN_3 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_3_prk_waked =
    issue[1] ? queue_2_prk_waked : queue_1_prk_waked;
  wire        queue_next_1_prk_waked =
    qvalid_pop[1] ? _queue_next_T_3_prk_waked : _GEN_25;
  wire [5:0]  _GEN_26 = _index_T_2 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire        _GEN_27 =
    _GEN
      ? (io_insts_dispatch_1_prj ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_26 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_3_prj_wake_by_ld =
    issue[1] ? queue_2_prj_wake_by_ld : queue_1_prj_wake_by_ld;
  wire        queue_next_1_prj_wake_by_ld =
    qvalid_pop[1] ? _queue_next_T_3_prj_wake_by_ld : _GEN_27;
  wire [5:0]  _GEN_28 = _index_T_2 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire        _GEN_29 =
    _GEN
      ? (io_insts_dispatch_1_prk ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_28 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_3_prk_wake_by_ld =
    issue[1] ? queue_2_prk_wake_by_ld : queue_1_prk_wake_by_ld;
  wire        queue_next_1_prk_wake_by_ld =
    qvalid_pop[1] ? _queue_next_T_3_prk_wake_by_ld : _GEN_29;
  wire        _GEN_30 = _GEN_6 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_5_prj_waked =
    issue[2] ? queue_3_prj_waked : queue_2_prj_waked;
  wire        queue_next_2_prj_waked =
    qvalid_pop[2] ? _queue_next_T_5_prj_waked : _GEN_30;
  wire        _GEN_31 = _GEN_6 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_5_prk_waked =
    issue[2] ? queue_3_prk_waked : queue_2_prk_waked;
  wire        queue_next_2_prk_waked =
    qvalid_pop[2] ? _queue_next_T_5_prk_waked : _GEN_31;
  wire [5:0]  _GEN_32 = _index_T_4 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire        _GEN_33 =
    _GEN
      ? (io_insts_dispatch_1_prj ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_32 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_5_prj_wake_by_ld =
    issue[2] ? queue_3_prj_wake_by_ld : queue_2_prj_wake_by_ld;
  wire        queue_next_2_prj_wake_by_ld =
    qvalid_pop[2] ? _queue_next_T_5_prj_wake_by_ld : _GEN_33;
  wire [5:0]  _GEN_34 = _index_T_4 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire        _GEN_35 =
    _GEN
      ? (io_insts_dispatch_1_prk ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_34 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_5_prk_wake_by_ld =
    issue[2] ? queue_3_prk_wake_by_ld : queue_2_prk_wake_by_ld;
  wire        queue_next_2_prk_wake_by_ld =
    qvalid_pop[2] ? _queue_next_T_5_prk_wake_by_ld : _GEN_35;
  wire        _GEN_36 = _GEN_9 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_7_prj_waked =
    issue[3] ? queue_4_prj_waked : queue_3_prj_waked;
  wire        queue_next_3_prj_waked =
    qvalid_pop[3] ? _queue_next_T_7_prj_waked : _GEN_36;
  wire        _GEN_37 = _GEN_9 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_7_prk_waked =
    issue[3] ? queue_4_prk_waked : queue_3_prk_waked;
  wire        queue_next_3_prk_waked =
    qvalid_pop[3] ? _queue_next_T_7_prk_waked : _GEN_37;
  wire [5:0]  _GEN_38 = _index_T_6 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire        _GEN_39 =
    _GEN
      ? (io_insts_dispatch_1_prj ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_38 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_7_prj_wake_by_ld =
    issue[3] ? queue_4_prj_wake_by_ld : queue_3_prj_wake_by_ld;
  wire        queue_next_3_prj_wake_by_ld =
    qvalid_pop[3] ? _queue_next_T_7_prj_wake_by_ld : _GEN_39;
  wire [5:0]  _GEN_40 = _index_T_6 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire        _GEN_41 =
    _GEN
      ? (io_insts_dispatch_1_prk ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_40 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_7_prk_wake_by_ld =
    issue[3] ? queue_4_prk_wake_by_ld : queue_3_prk_wake_by_ld;
  wire        queue_next_3_prk_wake_by_ld =
    qvalid_pop[3] ? _queue_next_T_7_prk_wake_by_ld : _GEN_41;
  wire        _GEN_42 = _GEN_12 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_9_prj_waked =
    issue[4] ? queue_5_prj_waked : queue_4_prj_waked;
  wire        queue_next_4_prj_waked =
    qvalid_pop[4] ? _queue_next_T_9_prj_waked : _GEN_42;
  wire        _GEN_43 = _GEN_12 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_9_prk_waked =
    issue[4] ? queue_5_prk_waked : queue_4_prk_waked;
  wire        queue_next_4_prk_waked =
    qvalid_pop[4] ? _queue_next_T_9_prk_waked : _GEN_43;
  wire [5:0]  _GEN_44 = _index_T_8 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire        _GEN_45 =
    _GEN
      ? (io_insts_dispatch_1_prj ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_44 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_9_prj_wake_by_ld =
    issue[4] ? queue_5_prj_wake_by_ld : queue_4_prj_wake_by_ld;
  wire        queue_next_4_prj_wake_by_ld =
    qvalid_pop[4] ? _queue_next_T_9_prj_wake_by_ld : _GEN_45;
  wire [5:0]  _GEN_46 = _index_T_8 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire        _GEN_47 =
    _GEN
      ? (io_insts_dispatch_1_prk ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_46 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_9_prk_wake_by_ld =
    issue[4] ? queue_5_prk_wake_by_ld : queue_4_prk_wake_by_ld;
  wire        queue_next_4_prk_wake_by_ld =
    qvalid_pop[4] ? _queue_next_T_9_prk_wake_by_ld : _GEN_47;
  wire        _GEN_48 = _GEN_15 ? io_prj_ready_1 : io_prj_ready_0;
  wire        queue_next_5_prj_waked = qvalid_pop[5] ? queue_5_prj_waked : _GEN_48;
  wire        _GEN_49 = _GEN_15 ? io_prk_ready_1 : io_prk_ready_0;
  wire        queue_next_5_prk_waked = qvalid_pop[5] ? queue_5_prk_waked : _GEN_49;
  wire [5:0]  _GEN_50 = _index_T_10 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire        _GEN_51 =
    _GEN
      ? (io_insts_dispatch_1_prj ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_50 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        queue_next_5_prj_wake_by_ld =
    qvalid_pop[5] ? queue_5_prj_wake_by_ld : _GEN_51;
  wire [5:0]  _GEN_52 = _index_T_10 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire        _GEN_53 =
    _GEN
      ? (io_insts_dispatch_1_prk ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_52 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        queue_next_5_prk_wake_by_ld =
    qvalid_pop[5] ? queue_5_prk_wake_by_ld : _GEN_53;
  always @(posedge clock) begin
    if (reset) begin
      queue_0_inst_prj <= 6'h0;
      queue_0_inst_prk <= 6'h0;
      queue_0_inst_rd_valid <= 1'h0;
      queue_0_inst_prd <= 6'h0;
      queue_0_inst_imm <= 32'h0;
      queue_0_inst_rob_index <= 5'h0;
      queue_0_inst_alu_op <= 4'h0;
      queue_0_inst_alu_rs1_sel <= 1'h0;
      queue_0_inst_alu_rs2_sel <= 2'h0;
      queue_0_inst_pc <= 32'h0;
      queue_0_prj_waked <= 1'h0;
      queue_0_prk_waked <= 1'h0;
      queue_0_prj_wake_by_ld <= 1'h0;
      queue_0_prk_wake_by_ld <= 1'h0;
      queue_1_inst_prj <= 6'h0;
      queue_1_inst_prk <= 6'h0;
      queue_1_inst_rd_valid <= 1'h0;
      queue_1_inst_prd <= 6'h0;
      queue_1_inst_imm <= 32'h0;
      queue_1_inst_rob_index <= 5'h0;
      queue_1_inst_alu_op <= 4'h0;
      queue_1_inst_alu_rs1_sel <= 1'h0;
      queue_1_inst_alu_rs2_sel <= 2'h0;
      queue_1_inst_pc <= 32'h0;
      queue_1_prj_waked <= 1'h0;
      queue_1_prk_waked <= 1'h0;
      queue_1_prj_wake_by_ld <= 1'h0;
      queue_1_prk_wake_by_ld <= 1'h0;
      queue_2_inst_prj <= 6'h0;
      queue_2_inst_prk <= 6'h0;
      queue_2_inst_rd_valid <= 1'h0;
      queue_2_inst_prd <= 6'h0;
      queue_2_inst_imm <= 32'h0;
      queue_2_inst_rob_index <= 5'h0;
      queue_2_inst_alu_op <= 4'h0;
      queue_2_inst_alu_rs1_sel <= 1'h0;
      queue_2_inst_alu_rs2_sel <= 2'h0;
      queue_2_inst_pc <= 32'h0;
      queue_2_prj_waked <= 1'h0;
      queue_2_prk_waked <= 1'h0;
      queue_2_prj_wake_by_ld <= 1'h0;
      queue_2_prk_wake_by_ld <= 1'h0;
      queue_3_inst_prj <= 6'h0;
      queue_3_inst_prk <= 6'h0;
      queue_3_inst_rd_valid <= 1'h0;
      queue_3_inst_prd <= 6'h0;
      queue_3_inst_imm <= 32'h0;
      queue_3_inst_rob_index <= 5'h0;
      queue_3_inst_alu_op <= 4'h0;
      queue_3_inst_alu_rs1_sel <= 1'h0;
      queue_3_inst_alu_rs2_sel <= 2'h0;
      queue_3_inst_pc <= 32'h0;
      queue_3_prj_waked <= 1'h0;
      queue_3_prk_waked <= 1'h0;
      queue_3_prj_wake_by_ld <= 1'h0;
      queue_3_prk_wake_by_ld <= 1'h0;
      queue_4_inst_prj <= 6'h0;
      queue_4_inst_prk <= 6'h0;
      queue_4_inst_rd_valid <= 1'h0;
      queue_4_inst_prd <= 6'h0;
      queue_4_inst_imm <= 32'h0;
      queue_4_inst_rob_index <= 5'h0;
      queue_4_inst_alu_op <= 4'h0;
      queue_4_inst_alu_rs1_sel <= 1'h0;
      queue_4_inst_alu_rs2_sel <= 2'h0;
      queue_4_inst_pc <= 32'h0;
      queue_4_prj_waked <= 1'h0;
      queue_4_prk_waked <= 1'h0;
      queue_4_prj_wake_by_ld <= 1'h0;
      queue_4_prk_wake_by_ld <= 1'h0;
      queue_5_inst_prj <= 6'h0;
      queue_5_inst_prk <= 6'h0;
      queue_5_inst_rd_valid <= 1'h0;
      queue_5_inst_prd <= 6'h0;
      queue_5_inst_imm <= 32'h0;
      queue_5_inst_rob_index <= 5'h0;
      queue_5_inst_alu_op <= 4'h0;
      queue_5_inst_alu_rs1_sel <= 1'h0;
      queue_5_inst_alu_rs2_sel <= 2'h0;
      queue_5_inst_pc <= 32'h0;
      queue_5_prj_waked <= 1'h0;
      queue_5_prk_waked <= 1'h0;
      queue_5_prj_wake_by_ld <= 1'h0;
      queue_5_prk_wake_by_ld <= 1'h0;
      num <= 4'h0;
      qvalid <= 6'h0;
    end
    else begin
      if (qvalid_pop[0]) begin
        if (issue[0]) begin
          queue_0_inst_prj <= queue_1_inst_prj;
          queue_0_inst_prk <= queue_1_inst_prk;
          queue_0_inst_rd_valid <= queue_1_inst_rd_valid;
          queue_0_inst_prd <= queue_1_inst_prd;
          queue_0_inst_imm <= queue_1_inst_imm;
          queue_0_inst_rob_index <= queue_1_inst_rob_index;
          queue_0_inst_alu_op <= queue_1_inst_alu_op;
          queue_0_inst_alu_rs1_sel <= queue_1_inst_alu_rs1_sel;
          queue_0_inst_alu_rs2_sel <= queue_1_inst_alu_rs2_sel;
          queue_0_inst_pc <= queue_1_inst_pc;
        end
      end
      else begin
        queue_0_inst_prj <= _GEN_1;
        queue_0_inst_prk <= _GEN_2;
        queue_0_inst_rd_valid <=
          _GEN_0 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_0_inst_prd <= _GEN_0 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_0_inst_imm <= _GEN_0 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_0_inst_rob_index <=
          _GEN_0 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_0_inst_alu_op <=
          _GEN_0 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_0_inst_alu_rs1_sel <=
          _GEN_0 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_0_inst_alu_rs2_sel <=
          _GEN_0 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_0_inst_pc <= _GEN_0 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_0_prj_waked <=
        queue_next_prj_waked
        | (|{~(|_queue_0_prj_wake_by_ld_T),
             (queue_next_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_0_prk_waked <=
        queue_next_prk_waked
        | (|{~(|_queue_0_prk_wake_by_ld_T),
             (queue_next_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_0_prj_wake_by_ld <=
        ~(|_queue_0_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_prj_wake_by_ld;
      queue_0_prk_wake_by_ld <=
        ~(|_queue_0_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_prk_wake_by_ld;
      if (qvalid_pop[1]) begin
        if (issue[1]) begin
          queue_1_inst_prj <= queue_2_inst_prj;
          queue_1_inst_prk <= queue_2_inst_prk;
          queue_1_inst_rd_valid <= queue_2_inst_rd_valid;
          queue_1_inst_prd <= queue_2_inst_prd;
          queue_1_inst_imm <= queue_2_inst_imm;
          queue_1_inst_rob_index <= queue_2_inst_rob_index;
          queue_1_inst_alu_op <= queue_2_inst_alu_op;
          queue_1_inst_alu_rs1_sel <= queue_2_inst_alu_rs1_sel;
          queue_1_inst_alu_rs2_sel <= queue_2_inst_alu_rs2_sel;
          queue_1_inst_pc <= queue_2_inst_pc;
        end
      end
      else begin
        queue_1_inst_prj <= _GEN_4;
        queue_1_inst_prk <= _GEN_5;
        queue_1_inst_rd_valid <=
          _GEN_3 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_1_inst_prd <= _GEN_3 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_1_inst_imm <= _GEN_3 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_1_inst_rob_index <=
          _GEN_3 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_1_inst_alu_op <=
          _GEN_3 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_1_inst_alu_rs1_sel <=
          _GEN_3 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_1_inst_alu_rs2_sel <=
          _GEN_3 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_1_inst_pc <= _GEN_3 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_1_prj_waked <=
        queue_next_1_prj_waked
        | (|{~(|_queue_1_prj_wake_by_ld_T),
             (queue_next_1_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_1_prk_waked <=
        queue_next_1_prk_waked
        | (|{~(|_queue_1_prk_wake_by_ld_T),
             (queue_next_1_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_1_prj_wake_by_ld <=
        ~(|_queue_1_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_1_prj_wake_by_ld;
      queue_1_prk_wake_by_ld <=
        ~(|_queue_1_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_1_prk_wake_by_ld;
      if (qvalid_pop[2]) begin
        if (issue[2]) begin
          queue_2_inst_prj <= queue_3_inst_prj;
          queue_2_inst_prk <= queue_3_inst_prk;
          queue_2_inst_rd_valid <= queue_3_inst_rd_valid;
          queue_2_inst_prd <= queue_3_inst_prd;
          queue_2_inst_imm <= queue_3_inst_imm;
          queue_2_inst_rob_index <= queue_3_inst_rob_index;
          queue_2_inst_alu_op <= queue_3_inst_alu_op;
          queue_2_inst_alu_rs1_sel <= queue_3_inst_alu_rs1_sel;
          queue_2_inst_alu_rs2_sel <= queue_3_inst_alu_rs2_sel;
          queue_2_inst_pc <= queue_3_inst_pc;
        end
      end
      else begin
        queue_2_inst_prj <= _GEN_7;
        queue_2_inst_prk <= _GEN_8;
        queue_2_inst_rd_valid <=
          _GEN_6 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_2_inst_prd <= _GEN_6 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_2_inst_imm <= _GEN_6 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_2_inst_rob_index <=
          _GEN_6 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_2_inst_alu_op <=
          _GEN_6 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_2_inst_alu_rs1_sel <=
          _GEN_6 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_2_inst_alu_rs2_sel <=
          _GEN_6 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_2_inst_pc <= _GEN_6 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_2_prj_waked <=
        queue_next_2_prj_waked
        | (|{~(|_queue_2_prj_wake_by_ld_T),
             (queue_next_2_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_2_prk_waked <=
        queue_next_2_prk_waked
        | (|{~(|_queue_2_prk_wake_by_ld_T),
             (queue_next_2_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_2_prj_wake_by_ld <=
        ~(|_queue_2_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_2_prj_wake_by_ld;
      queue_2_prk_wake_by_ld <=
        ~(|_queue_2_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_2_prk_wake_by_ld;
      if (qvalid_pop[3]) begin
        if (issue[3]) begin
          queue_3_inst_prj <= queue_4_inst_prj;
          queue_3_inst_prk <= queue_4_inst_prk;
          queue_3_inst_rd_valid <= queue_4_inst_rd_valid;
          queue_3_inst_prd <= queue_4_inst_prd;
          queue_3_inst_imm <= queue_4_inst_imm;
          queue_3_inst_rob_index <= queue_4_inst_rob_index;
          queue_3_inst_alu_op <= queue_4_inst_alu_op;
          queue_3_inst_alu_rs1_sel <= queue_4_inst_alu_rs1_sel;
          queue_3_inst_alu_rs2_sel <= queue_4_inst_alu_rs2_sel;
          queue_3_inst_pc <= queue_4_inst_pc;
        end
      end
      else begin
        queue_3_inst_prj <= _GEN_10;
        queue_3_inst_prk <= _GEN_11;
        queue_3_inst_rd_valid <=
          _GEN_9 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_3_inst_prd <= _GEN_9 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_3_inst_imm <= _GEN_9 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_3_inst_rob_index <=
          _GEN_9 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_3_inst_alu_op <=
          _GEN_9 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_3_inst_alu_rs1_sel <=
          _GEN_9 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_3_inst_alu_rs2_sel <=
          _GEN_9 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_3_inst_pc <= _GEN_9 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_3_prj_waked <=
        queue_next_3_prj_waked
        | (|{~(|_queue_3_prj_wake_by_ld_T),
             (queue_next_3_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_3_prk_waked <=
        queue_next_3_prk_waked
        | (|{~(|_queue_3_prk_wake_by_ld_T),
             (queue_next_3_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_3_prj_wake_by_ld <=
        ~(|_queue_3_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_3_prj_wake_by_ld;
      queue_3_prk_wake_by_ld <=
        ~(|_queue_3_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_3_prk_wake_by_ld;
      if (qvalid_pop[4]) begin
        if (issue[4]) begin
          queue_4_inst_prj <= queue_5_inst_prj;
          queue_4_inst_prk <= queue_5_inst_prk;
          queue_4_inst_rd_valid <= queue_5_inst_rd_valid;
          queue_4_inst_prd <= queue_5_inst_prd;
          queue_4_inst_imm <= queue_5_inst_imm;
          queue_4_inst_rob_index <= queue_5_inst_rob_index;
          queue_4_inst_alu_op <= queue_5_inst_alu_op;
          queue_4_inst_alu_rs1_sel <= queue_5_inst_alu_rs1_sel;
          queue_4_inst_alu_rs2_sel <= queue_5_inst_alu_rs2_sel;
          queue_4_inst_pc <= queue_5_inst_pc;
        end
      end
      else begin
        queue_4_inst_prj <= _GEN_13;
        queue_4_inst_prk <= _GEN_14;
        queue_4_inst_rd_valid <=
          _GEN_12 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_4_inst_prd <= _GEN_12 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_4_inst_imm <= _GEN_12 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_4_inst_rob_index <=
          _GEN_12 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_4_inst_alu_op <=
          _GEN_12 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_4_inst_alu_rs1_sel <=
          _GEN_12 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_4_inst_alu_rs2_sel <=
          _GEN_12 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_4_inst_pc <= _GEN_12 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_4_prj_waked <=
        queue_next_4_prj_waked
        | (|{~(|_queue_4_prj_wake_by_ld_T),
             (queue_next_4_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_4_prk_waked <=
        queue_next_4_prk_waked
        | (|{~(|_queue_4_prk_wake_by_ld_T),
             (queue_next_4_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_4_prj_wake_by_ld <=
        ~(|_queue_4_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_4_prj_wake_by_ld;
      queue_4_prk_wake_by_ld <=
        ~(|_queue_4_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_4_prk_wake_by_ld;
      if (qvalid_pop[5]) begin
      end
      else begin
        queue_5_inst_prj <= _GEN_16;
        queue_5_inst_prk <= _GEN_17;
        queue_5_inst_rd_valid <=
          _GEN_15 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_5_inst_prd <= _GEN_15 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_5_inst_imm <= _GEN_15 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_5_inst_rob_index <=
          _GEN_15 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_5_inst_alu_op <=
          _GEN_15 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_5_inst_alu_rs1_sel <=
          _GEN_15 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_5_inst_alu_rs2_sel <=
          _GEN_15 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_5_inst_pc <= _GEN_15 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_5_prj_waked <=
        queue_next_5_prj_waked
        | (|{~(|_queue_5_prj_wake_by_ld_T),
             (queue_next_5_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_5_prk_waked <=
        queue_next_5_prk_waked
        | (|{~(|_queue_5_prk_wake_by_ld_T),
             (queue_next_5_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_5_prj_wake_by_ld <=
        ~(|_queue_5_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_5_prj_wake_by_ld;
      queue_5_prk_wake_by_ld <=
        ~(|_queue_5_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_5_prk_wake_by_ld;
      if (io_flush) begin
        num <= 4'h0;
        qvalid <= 6'h0;
      end
      else begin
        if (io_stall | qvalid[4])
          num <= _num_pop_T_2;
        else
          num <= 4'(_num_pop_T_2 + {2'h0, ins_num});
        if (io_stall) begin
          if (|_qvalid_pop_T)
            qvalid <= _qvalid_pop_T_3;
        end
        else if (ins_num == 2'h2)
          qvalid <= {qvalid_pop[3:0], 2'h3};
        else if (ins_num == 2'h1)
          qvalid <= {qvalid_pop[4:0], 1'h1};
        else if (|_qvalid_pop_T)
          qvalid <= _qvalid_pop_T_3;
      end
    end
  end // always @(posedge)
  assign io_insts_issue_0_inst_prj = queue_0_inst_prj;
  assign io_insts_issue_0_inst_prk = queue_0_inst_prk;
  assign io_insts_issue_0_inst_rd_valid = queue_0_inst_rd_valid;
  assign io_insts_issue_0_inst_prd = queue_0_inst_prd;
  assign io_insts_issue_0_inst_imm = queue_0_inst_imm;
  assign io_insts_issue_0_inst_rob_index = queue_0_inst_rob_index;
  assign io_insts_issue_0_inst_alu_op = queue_0_inst_alu_op;
  assign io_insts_issue_0_inst_alu_rs1_sel = queue_0_inst_alu_rs1_sel;
  assign io_insts_issue_0_inst_alu_rs2_sel = queue_0_inst_alu_rs2_sel;
  assign io_insts_issue_0_inst_pc = queue_0_inst_pc;
  assign io_insts_issue_1_inst_prj = queue_1_inst_prj;
  assign io_insts_issue_1_inst_prk = queue_1_inst_prk;
  assign io_insts_issue_1_inst_rd_valid = queue_1_inst_rd_valid;
  assign io_insts_issue_1_inst_prd = queue_1_inst_prd;
  assign io_insts_issue_1_inst_imm = queue_1_inst_imm;
  assign io_insts_issue_1_inst_rob_index = queue_1_inst_rob_index;
  assign io_insts_issue_1_inst_alu_op = queue_1_inst_alu_op;
  assign io_insts_issue_1_inst_alu_rs1_sel = queue_1_inst_alu_rs1_sel;
  assign io_insts_issue_1_inst_alu_rs2_sel = queue_1_inst_alu_rs2_sel;
  assign io_insts_issue_1_inst_pc = queue_1_inst_pc;
  assign io_insts_issue_2_inst_prj = queue_2_inst_prj;
  assign io_insts_issue_2_inst_prk = queue_2_inst_prk;
  assign io_insts_issue_2_inst_rd_valid = queue_2_inst_rd_valid;
  assign io_insts_issue_2_inst_prd = queue_2_inst_prd;
  assign io_insts_issue_2_inst_imm = queue_2_inst_imm;
  assign io_insts_issue_2_inst_rob_index = queue_2_inst_rob_index;
  assign io_insts_issue_2_inst_alu_op = queue_2_inst_alu_op;
  assign io_insts_issue_2_inst_alu_rs1_sel = queue_2_inst_alu_rs1_sel;
  assign io_insts_issue_2_inst_alu_rs2_sel = queue_2_inst_alu_rs2_sel;
  assign io_insts_issue_2_inst_pc = queue_2_inst_pc;
  assign io_insts_issue_3_inst_prj = queue_3_inst_prj;
  assign io_insts_issue_3_inst_prk = queue_3_inst_prk;
  assign io_insts_issue_3_inst_rd_valid = queue_3_inst_rd_valid;
  assign io_insts_issue_3_inst_prd = queue_3_inst_prd;
  assign io_insts_issue_3_inst_imm = queue_3_inst_imm;
  assign io_insts_issue_3_inst_rob_index = queue_3_inst_rob_index;
  assign io_insts_issue_3_inst_alu_op = queue_3_inst_alu_op;
  assign io_insts_issue_3_inst_alu_rs1_sel = queue_3_inst_alu_rs1_sel;
  assign io_insts_issue_3_inst_alu_rs2_sel = queue_3_inst_alu_rs2_sel;
  assign io_insts_issue_3_inst_pc = queue_3_inst_pc;
  assign io_insts_issue_4_inst_prj = queue_4_inst_prj;
  assign io_insts_issue_4_inst_prk = queue_4_inst_prk;
  assign io_insts_issue_4_inst_rd_valid = queue_4_inst_rd_valid;
  assign io_insts_issue_4_inst_prd = queue_4_inst_prd;
  assign io_insts_issue_4_inst_imm = queue_4_inst_imm;
  assign io_insts_issue_4_inst_rob_index = queue_4_inst_rob_index;
  assign io_insts_issue_4_inst_alu_op = queue_4_inst_alu_op;
  assign io_insts_issue_4_inst_alu_rs1_sel = queue_4_inst_alu_rs1_sel;
  assign io_insts_issue_4_inst_alu_rs2_sel = queue_4_inst_alu_rs2_sel;
  assign io_insts_issue_4_inst_pc = queue_4_inst_pc;
  assign io_insts_issue_5_inst_prj = queue_5_inst_prj;
  assign io_insts_issue_5_inst_prk = queue_5_inst_prk;
  assign io_insts_issue_5_inst_rd_valid = queue_5_inst_rd_valid;
  assign io_insts_issue_5_inst_prd = queue_5_inst_prd;
  assign io_insts_issue_5_inst_imm = queue_5_inst_imm;
  assign io_insts_issue_5_inst_rob_index = queue_5_inst_rob_index;
  assign io_insts_issue_5_inst_alu_op = queue_5_inst_alu_op;
  assign io_insts_issue_5_inst_alu_rs1_sel = queue_5_inst_alu_rs1_sel;
  assign io_insts_issue_5_inst_alu_rs2_sel = queue_5_inst_alu_rs2_sel;
  assign io_insts_issue_5_inst_pc = queue_5_inst_pc;
  assign io_issue_req_0 =
    qvalid[0] & queue_0_prj_waked & queue_0_prk_waked
    & ~((queue_0_prj_wake_by_ld & (queue_0_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_0_prk_wake_by_ld & (queue_0_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_1 =
    qvalid[1] & queue_1_prj_waked & queue_1_prk_waked
    & ~((queue_1_prj_wake_by_ld & (queue_1_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_1_prk_wake_by_ld & (queue_1_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_2 =
    qvalid[2] & queue_2_prj_waked & queue_2_prk_waked
    & ~((queue_2_prj_wake_by_ld & (queue_2_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_2_prk_wake_by_ld & (queue_2_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_3 =
    qvalid[3] & queue_3_prj_waked & queue_3_prk_waked
    & ~((queue_3_prj_wake_by_ld & (queue_3_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_3_prk_wake_by_ld & (queue_3_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_4 =
    qvalid[4] & queue_4_prj_waked & queue_4_prk_waked
    & ~((queue_4_prj_wake_by_ld & (queue_4_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_4_prk_wake_by_ld & (queue_4_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_5 =
    qvalid[5] & queue_5_prj_waked & queue_5_prk_waked
    & ~((queue_5_prj_wake_by_ld & (queue_5_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_5_prk_wake_by_ld & (queue_5_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_elem_num = num;
  assign io_full = qvalid[4];
endmodule

