// Generated by CIRCT firtool-1.62.0
module ALU(
  input  [31:0] io_src1,
                io_src2,
  input  [3:0]  io_alu_op,
  output [31:0] io_alu_out
);

  wire [62:0]       _result_T_12 = {31'h0, io_src1} << io_src2[4:0];
  wire [15:0][31:0] _GEN =
    {{32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {io_src1 >> io_src2[4:0]},
     {io_src1 >> io_src2[4:0]},
     {_result_T_12[31:0]},
     {io_src1 ^ io_src2},
     {io_src1 | io_src2},
     {io_src1 & io_src2},
     {~(io_src1 | io_src2)},
     {{31'h0, io_src1 < io_src2}},
     {{31'h0, $signed(io_src1) < $signed(io_src2)}},
     {32'(io_src1 - io_src2)},
     {32'(io_src1 + io_src2)}};
  assign io_alu_out = _GEN[io_alu_op];
endmodule

