// Generated by CIRCT firtool-1.62.0
module Decode(
  input  [31:0] io_inst,
  output [4:0]  io_rj,
                io_rk,
                io_rd,
  output        io_rd_valid,
  output [31:0] io_imm,
  output [4:0]  io_alu_op,
  output        io_alu_rs1_sel,
  output [1:0]  io_alu_rs2_sel,
  output [3:0]  io_br_type,
  output [4:0]  io_mem_type,
  output [12:0] io_priv_vec,
  output [2:0]  io_fu_id,
  output [7:0]  io_exception
);

  wire              _control_signal_T_1 = {io_inst[31:10], io_inst[4:0]} == 27'h300;
  wire              _control_signal_T_3 = io_inst[31:5] == 27'h300;
  wire              _control_signal_T_5 = io_inst[31:5] == 27'h320;
  wire              _control_signal_T_7 = io_inst[31:15] == 17'h20;
  wire              _control_signal_T_9 = io_inst[31:15] == 17'h22;
  wire              _control_signal_T_11 = io_inst[31:15] == 17'h24;
  wire              _control_signal_T_13 = io_inst[31:15] == 17'h25;
  wire              _control_signal_T_15 = io_inst[31:15] == 17'h28;
  wire              _control_signal_T_17 = io_inst[31:15] == 17'h29;
  wire              _control_signal_T_19 = io_inst[31:15] == 17'h2A;
  wire              _control_signal_T_21 = io_inst[31:15] == 17'h2B;
  wire              _control_signal_T_23 = io_inst[31:15] == 17'h2E;
  wire              _control_signal_T_25 = io_inst[31:15] == 17'h2F;
  wire              _control_signal_T_27 = io_inst[31:15] == 17'h30;
  wire              _control_signal_T_29 = io_inst[31:15] == 17'h38;
  wire              _control_signal_T_31 = io_inst[31:15] == 17'h39;
  wire              _control_signal_T_33 = io_inst[31:15] == 17'h3A;
  wire              _control_signal_T_35 = io_inst[31:15] == 17'h40;
  wire              _control_signal_T_37 = io_inst[31:15] == 17'h41;
  wire              _control_signal_T_39 = io_inst[31:15] == 17'h42;
  wire              _control_signal_T_41 = io_inst[31:15] == 17'h43;
  wire              _control_signal_T_43 = io_inst[31:15] == 17'h54;
  wire              _control_signal_T_45 = io_inst[31:15] == 17'h56;
  wire              _control_signal_T_47 = io_inst[31:15] == 17'h81;
  wire              _control_signal_T_49 = io_inst[31:15] == 17'h89;
  wire              _control_signal_T_51 = io_inst[31:15] == 17'h91;
  wire              _control_signal_T_53 = io_inst[31:22] == 10'h8;
  wire              _control_signal_T_55 = io_inst[31:22] == 10'h9;
  wire              _control_signal_T_57 = io_inst[31:22] == 10'hA;
  wire              _control_signal_T_59 = io_inst[31:22] == 10'hD;
  wire              _control_signal_T_61 = io_inst[31:22] == 10'hE;
  wire              _control_signal_T_63 = io_inst[31:22] == 10'hF;
  wire [12:0]       _GEN = {io_inst[31:24], io_inst[9:5]};
  wire              _control_signal_T_65 = _GEN == 13'h80;
  wire              _control_signal_T_67 = _GEN == 13'h81;
  wire              _control_signal_T_69 = io_inst[31:24] == 8'h4;
  wire              _control_signal_T_71 = io_inst == 32'h6483800;
  wire              _control_signal_T_73 = io_inst[31:15] == 17'hC91;
  wire              _control_signal_T_75 = io_inst[31:25] == 7'hA;
  wire              _control_signal_T_77 = io_inst[31:25] == 7'hE;
  wire              _control_signal_T_79 = io_inst[31:22] == 10'hA0;
  wire              _control_signal_T_81 = io_inst[31:22] == 10'hA1;
  wire              _control_signal_T_83 = io_inst[31:22] == 10'hA2;
  wire              _control_signal_T_85 = io_inst[31:22] == 10'hA4;
  wire              _control_signal_T_87 = io_inst[31:22] == 10'hA5;
  wire              _control_signal_T_89 = io_inst[31:22] == 10'hA6;
  wire              _control_signal_T_91 = io_inst[31:22] == 10'hA8;
  wire              _control_signal_T_93 = io_inst[31:22] == 10'hA9;
  wire              _control_signal_T_95 = io_inst[31:26] == 6'h13;
  wire              _control_signal_T_97 = io_inst[31:26] == 6'h14;
  wire              _control_signal_T_338 = io_inst[31:26] == 6'h15;
  wire              _control_signal_T_101 = io_inst[31:26] == 6'h16;
  wire              _control_signal_T_103 = io_inst[31:26] == 6'h17;
  wire              _control_signal_T_105 = io_inst[31:26] == 6'h18;
  wire              _control_signal_T_107 = io_inst[31:26] == 6'h19;
  wire              _control_signal_T_109 = io_inst[31:26] == 6'h1A;
  wire              _control_signal_T_167 = io_inst[31:26] == 6'h1B;
  wire              _GEN_0 =
    _control_signal_T_101 | _control_signal_T_103 | _control_signal_T_105
    | _control_signal_T_107 | _control_signal_T_109;
  wire              _GEN_1 = _control_signal_T_97 | _control_signal_T_338;
  wire              _GEN_2 =
    _control_signal_T_91 | _control_signal_T_93 | _control_signal_T_95;
  wire              _GEN_3 = _control_signal_T_75 | _control_signal_T_77;
  wire              _GEN_4 = _control_signal_T_71 | _control_signal_T_73 | _GEN_3;
  wire              _GEN_5 =
    _control_signal_T_59 | _control_signal_T_61 | _control_signal_T_63;
  wire              _GEN_6 =
    _control_signal_T_47 | _control_signal_T_49 | _control_signal_T_51
    | _control_signal_T_53 | _control_signal_T_55 | _control_signal_T_57 | _GEN_5;
  wire              _GEN_7 = _control_signal_T_43 | _control_signal_T_45;
  wire              _GEN_8 =
    _control_signal_T_7 | _control_signal_T_9 | _control_signal_T_11
    | _control_signal_T_13 | _control_signal_T_15 | _control_signal_T_17
    | _control_signal_T_19 | _control_signal_T_21 | _control_signal_T_23
    | _control_signal_T_25 | _control_signal_T_27 | _control_signal_T_29
    | _control_signal_T_31 | _control_signal_T_33 | _control_signal_T_35
    | _control_signal_T_37 | _control_signal_T_39 | _control_signal_T_41;
  wire              _GEN_9 = _control_signal_T_3 | _control_signal_T_5;
  wire              _GEN_10 = _control_signal_T_1 | _GEN_9;
  wire              _GEN_11 =
    _control_signal_T_91 | _control_signal_T_93 | _control_signal_T_95 | _GEN_1;
  wire              _GEN_12 =
    _control_signal_T_85 | _control_signal_T_87 | _control_signal_T_89;
  wire              _GEN_13 =
    _control_signal_T_75 | _control_signal_T_77 | _control_signal_T_79
    | _control_signal_T_81 | _control_signal_T_83;
  wire              _GEN_14 = _control_signal_T_67 | _control_signal_T_69;
  wire              _GEN_15 = _control_signal_T_71 | _control_signal_T_73;
  wire              _GEN_16 = _control_signal_T_65 | _GEN_14;
  wire              _GEN_17 = _control_signal_T_3 | _control_signal_T_5 | _GEN_8;
  wire              _GEN_18 = _control_signal_T_1 | _GEN_17;
  wire [3:0]        _control_signal_T_301 = _control_signal_T_63 ? 4'h7 : 4'h0;
  wire [3:0]        _control_signal_T_302 =
    _control_signal_T_61 ? 4'h6 : _control_signal_T_301;
  wire [3:0]        _control_signal_T_303 =
    _control_signal_T_59 ? 4'h5 : _control_signal_T_302;
  wire [3:0]        _control_signal_T_304 =
    _control_signal_T_57 ? 4'h0 : _control_signal_T_303;
  wire [3:0]        _control_signal_T_305 =
    _control_signal_T_55 ? 4'h3 : _control_signal_T_304;
  wire [3:0]        _control_signal_T_306 =
    _control_signal_T_53 ? 4'h2 : _control_signal_T_305;
  wire [3:0]        _control_signal_T_307 =
    _control_signal_T_51 ? 4'hA : _control_signal_T_306;
  wire [3:0]        _control_signal_T_308 =
    _control_signal_T_49 ? 4'h9 : _control_signal_T_307;
  wire [3:0]        _control_signal_T_309 =
    _control_signal_T_47 ? 4'h8 : _control_signal_T_308;
  wire [3:0]        _control_signal_T_311 = _GEN_7 ? 4'h0 : _control_signal_T_309;
  wire [3:0]        _control_signal_T_312 =
    _control_signal_T_41 ? 4'h7 : _control_signal_T_311;
  wire [3:0]        _control_signal_T_313 =
    _control_signal_T_39 ? 4'h6 : _control_signal_T_312;
  wire [3:0]        _control_signal_T_314 =
    _control_signal_T_37 ? 4'h5 : _control_signal_T_313;
  wire [3:0]        _control_signal_T_315 =
    _control_signal_T_35 ? 4'h4 : _control_signal_T_314;
  wire [3:0]        _control_signal_T_316 =
    _control_signal_T_33 ? 4'h2 : _control_signal_T_315;
  wire [3:0]        _control_signal_T_317 =
    _control_signal_T_31 ? 4'h1 : _control_signal_T_316;
  wire [3:0]        _control_signal_T_318 =
    _control_signal_T_29 ? 4'h0 : _control_signal_T_317;
  wire [3:0]        _control_signal_T_319 =
    _control_signal_T_27 ? 4'hA : _control_signal_T_318;
  wire [3:0]        _control_signal_T_320 =
    _control_signal_T_25 ? 4'h9 : _control_signal_T_319;
  wire [3:0]        _control_signal_T_321 =
    _control_signal_T_23 ? 4'h8 : _control_signal_T_320;
  wire [3:0]        _control_signal_T_322 =
    _control_signal_T_21 ? 4'h7 : _control_signal_T_321;
  wire [3:0]        _control_signal_T_323 =
    _control_signal_T_19 ? 4'h6 : _control_signal_T_322;
  wire [3:0]        _control_signal_T_324 =
    _control_signal_T_17 ? 4'h5 : _control_signal_T_323;
  wire [3:0]        _control_signal_T_325 =
    _control_signal_T_15 ? 4'h4 : _control_signal_T_324;
  wire [3:0]        _control_signal_T_326 =
    _control_signal_T_13 ? 4'h3 : _control_signal_T_325;
  wire [3:0]        _control_signal_T_327 =
    _control_signal_T_11 ? 4'h2 : _control_signal_T_326;
  wire [3:0]        _control_signal_T_328 =
    _control_signal_T_9 ? 4'h1 : _control_signal_T_327;
  wire [3:0]        control_signal_3 =
    _control_signal_T_1 | _control_signal_T_3 | _control_signal_T_5 | _control_signal_T_7
      ? 4'h0
      : _control_signal_T_328;
  wire              _GEN_19 =
    _control_signal_T_79 | _control_signal_T_81 | _control_signal_T_83
    | _control_signal_T_85 | _control_signal_T_87 | _control_signal_T_89
    | _control_signal_T_91 | _control_signal_T_93;
  wire              _GEN_20 =
    _control_signal_T_43 | _control_signal_T_45 | _control_signal_T_47
    | _control_signal_T_49 | _control_signal_T_51 | _control_signal_T_53
    | _control_signal_T_55 | _control_signal_T_57 | _control_signal_T_59
    | _control_signal_T_61 | _control_signal_T_63 | _control_signal_T_65
    | _control_signal_T_67 | _control_signal_T_69 | _control_signal_T_71
    | _control_signal_T_73 | _control_signal_T_75 | _control_signal_T_77 | _GEN_19;
  wire [1:0]        _control_signal_T_421 =
    _GEN_20 | ~(_control_signal_T_95 | ~(_control_signal_T_97 | ~_control_signal_T_338))
      ? 2'h1
      : 2'h2;
  wire [1:0]        _control_signal_T_439 = _GEN_8 ? 2'h0 : _control_signal_T_421;
  wire [1:0]        _control_signal_T_440 =
    _control_signal_T_5 ? 2'h2 : _control_signal_T_439;
  wire [1:0]        _control_signal_T_441 =
    _control_signal_T_3 ? 2'h3 : _control_signal_T_440;
  wire [3:0]        _control_signal_T_442 = _control_signal_T_167 ? 4'hB : 4'h0;
  wire [3:0]        _control_signal_T_443 =
    _control_signal_T_109 ? 4'hA : _control_signal_T_442;
  wire [3:0]        _control_signal_T_444 =
    _control_signal_T_107 ? 4'h9 : _control_signal_T_443;
  wire [3:0]        _control_signal_T_445 =
    _control_signal_T_105 ? 4'h8 : _control_signal_T_444;
  wire [3:0]        _control_signal_T_446 =
    _control_signal_T_103 ? 4'h7 : _control_signal_T_445;
  wire [3:0]        _control_signal_T_447 =
    _control_signal_T_101 ? 4'h6 : _control_signal_T_446;
  wire [3:0]        _control_signal_T_448 =
    _control_signal_T_338 ? 4'h5 : _control_signal_T_447;
  wire [3:0]        _control_signal_T_449 =
    _control_signal_T_97 ? 4'h4 : _control_signal_T_448;
  wire [3:0]        _control_signal_T_450 =
    _control_signal_T_95 ? 4'h3 : _control_signal_T_449;
  wire [4:0]        _control_signal_T_506 = _control_signal_T_93 ? 5'hD : 5'h0;
  wire [4:0]        _control_signal_T_507 =
    _control_signal_T_91 ? 5'hC : _control_signal_T_506;
  wire [4:0]        _control_signal_T_508 =
    _control_signal_T_89 ? 5'h12 : _control_signal_T_507;
  wire [4:0]        _control_signal_T_509 =
    _control_signal_T_87 ? 5'h11 : _control_signal_T_508;
  wire [4:0]        _control_signal_T_510 =
    _control_signal_T_85 ? 5'h10 : _control_signal_T_509;
  wire [4:0]        _control_signal_T_511 =
    _control_signal_T_83 ? 5'hA : _control_signal_T_510;
  wire [4:0]        _control_signal_T_512 =
    _control_signal_T_81 ? 5'h9 : _control_signal_T_511;
  wire [4:0]        _control_signal_T_513 =
    _control_signal_T_79 ? 5'h8 : _control_signal_T_512;
  wire              _GEN_21 =
    _control_signal_T_101 | _control_signal_T_103 | _control_signal_T_105
    | _control_signal_T_107 | _control_signal_T_109 | _control_signal_T_167;
  wire              _GEN_22 =
    _control_signal_T_95 | _control_signal_T_97 | _control_signal_T_338 | _GEN_21;
  wire [2:0]        _control_signal_T_560 = _GEN_22 ? 3'h1 : 3'h2;
  wire [2:0]        _control_signal_T_568 = _GEN_19 ? 3'h3 : _control_signal_T_560;
  wire [2:0]        _control_signal_T_570 = _GEN_3 ? 3'h4 : _control_signal_T_568;
  wire              _GEN_23 =
    _control_signal_T_65 | _control_signal_T_67 | _control_signal_T_69 | _GEN_15;
  wire [2:0]        _control_signal_T_575 = _GEN_23 ? 3'h2 : _control_signal_T_570;
  wire [2:0]        _control_signal_T_584 = _GEN_6 ? 3'h4 : _control_signal_T_575;
  wire              _GEN_24 =
    _control_signal_T_29 | _control_signal_T_31 | _control_signal_T_33
    | _control_signal_T_35 | _control_signal_T_37 | _control_signal_T_39
    | _control_signal_T_41 | _GEN_7;
  wire [2:0]        _control_signal_T_593 = _GEN_24 ? 3'h2 : _control_signal_T_584;
  wire [2:0]        _control_signal_T_604 =
    _control_signal_T_7 | _control_signal_T_9 | _control_signal_T_11
    | _control_signal_T_13 | _control_signal_T_15 | _control_signal_T_17
    | _control_signal_T_19 | _control_signal_T_21 | _control_signal_T_23
    | _control_signal_T_25 | _control_signal_T_27
      ? 3'h4
      : _control_signal_T_593;
  wire [2:0]        _control_signal_T_606 = _GEN_9 ? 3'h0 : _control_signal_T_604;
  wire [1:0]        _control_signal_T_716 =
    _control_signal_T_3 | _control_signal_T_5 | _control_signal_T_7 | _control_signal_T_9
    | _control_signal_T_11 | _control_signal_T_13 | _control_signal_T_15
    | _control_signal_T_17 | _control_signal_T_19 | _control_signal_T_21
    | _control_signal_T_23 | _control_signal_T_25 | _control_signal_T_27
    | _control_signal_T_29 | _control_signal_T_31 | _control_signal_T_33
    | _control_signal_T_35 | _control_signal_T_37 | _control_signal_T_39
    | _control_signal_T_41 | _control_signal_T_43 | _control_signal_T_45
    | _control_signal_T_47 | _control_signal_T_49 | _control_signal_T_51
    | _control_signal_T_53 | _control_signal_T_55 | _control_signal_T_57
    | _control_signal_T_59 | _control_signal_T_61 | _control_signal_T_63
    | _control_signal_T_65 | _control_signal_T_67 | _control_signal_T_69
    | _control_signal_T_71 | _control_signal_T_73 | _control_signal_T_75
    | _control_signal_T_77 | _control_signal_T_79 | _control_signal_T_81
    | _control_signal_T_83 | _control_signal_T_85 | _control_signal_T_87
    | _control_signal_T_89 | _control_signal_T_91 | _control_signal_T_93
    | _control_signal_T_95 | _control_signal_T_97
      ? 2'h0
      : {1'h0, _control_signal_T_338};
  wire [1:0]        control_signal_10 =
    _control_signal_T_1 ? 2'h2 : _control_signal_T_716;
  wire [3:0]        _control_signal_T_724 = _GEN_1 ? 4'h6 : {1'h0, _GEN_21, 2'h0};
  wire [3:0]        _control_signal_T_725 =
    _control_signal_T_95 ? 4'h4 : _control_signal_T_724;
  wire [3:0]        _control_signal_T_733 = _GEN_19 ? 4'h3 : _control_signal_T_725;
  wire [3:0]        _control_signal_T_735 = _GEN_3 ? 4'h5 : _control_signal_T_733;
  wire [3:0]        _control_signal_T_736 =
    _control_signal_T_73 ? 4'h0 : _control_signal_T_735;
  wire [3:0]        _control_signal_T_737 =
    _control_signal_T_71 ? 4'h9 : _control_signal_T_736;
  wire [3:0]        _control_signal_T_740 = _GEN_16 ? 4'h7 : _control_signal_T_737;
  wire [3:0]        _control_signal_T_743 = _GEN_5 ? 4'h2 : _control_signal_T_740;
  wire [3:0]        _control_signal_T_746 =
    _control_signal_T_53 | _control_signal_T_55 | _control_signal_T_57
      ? 4'h3
      : _control_signal_T_743;
  wire [3:0]        _control_signal_T_749 =
    _control_signal_T_47 | _control_signal_T_49 | _control_signal_T_51
      ? 4'h1
      : _control_signal_T_746;
  wire [3:0]        _control_signal_T_771 =
    _control_signal_T_3 | _control_signal_T_5 | _control_signal_T_7 | _control_signal_T_9
    | _control_signal_T_11 | _control_signal_T_13 | _control_signal_T_15
    | _control_signal_T_17 | _control_signal_T_19 | _control_signal_T_21
    | _control_signal_T_23 | _control_signal_T_25 | _control_signal_T_27 | _GEN_24
      ? 4'h0
      : _control_signal_T_749;
  wire [3:0]        control_signal_11 =
    _control_signal_T_1 ? 4'h8 : _control_signal_T_771;
  wire [12:0]       _control_signal_T_791 = _control_signal_T_73 ? 13'h201 : 13'h0;
  wire [12:0]       _control_signal_T_792 =
    _control_signal_T_71 ? 13'h9 : _control_signal_T_791;
  wire [12:0]       _control_signal_T_793 =
    _control_signal_T_69 ? 13'h5 : _control_signal_T_792;
  wire [12:0]       _control_signal_T_794 =
    _control_signal_T_67 ? 13'h3 : _control_signal_T_793;
  wire [12:0]       _control_signal_T_795 =
    _control_signal_T_65 ? 13'h1 : _control_signal_T_794;
  wire [12:0]       _control_signal_T_826 =
    _control_signal_T_3 | _control_signal_T_5 | _control_signal_T_7 | _control_signal_T_9
    | _control_signal_T_11 | _control_signal_T_13 | _control_signal_T_15
    | _control_signal_T_17 | _control_signal_T_19 | _control_signal_T_21
    | _control_signal_T_23 | _control_signal_T_25 | _control_signal_T_27
    | _control_signal_T_29 | _control_signal_T_31 | _control_signal_T_33
    | _control_signal_T_35 | _control_signal_T_37 | _control_signal_T_39
    | _control_signal_T_41 | _control_signal_T_43 | _control_signal_T_45 | _GEN_6
      ? 13'h0
      : _control_signal_T_795;
  wire [7:0]        _control_signal_T_859 =
    _control_signal_T_47 | _control_signal_T_49 | _control_signal_T_51
    | _control_signal_T_53 | _control_signal_T_55 | _control_signal_T_57
    | _control_signal_T_59 | _control_signal_T_61 | _control_signal_T_63
    | _control_signal_T_65 | _control_signal_T_67 | _control_signal_T_69
    | _control_signal_T_71 | _control_signal_T_73 | _control_signal_T_75
    | _control_signal_T_77 | _control_signal_T_79 | _control_signal_T_81
    | _control_signal_T_83 | _control_signal_T_85 | _control_signal_T_87
    | _control_signal_T_89 | _control_signal_T_91 | _control_signal_T_93 | _GEN_22
      ? 8'h0
      : 8'h8D;
  wire [7:0]        _control_signal_T_860 =
    _control_signal_T_45 ? 8'h8B : _control_signal_T_859;
  wire [7:0]        _control_signal_T_861 =
    _control_signal_T_43 ? 8'h8C : _control_signal_T_860;
  wire [4:0]        _io_rk_T_3 =
    ~_control_signal_T_1
    & (_GEN_17 | ~_GEN_7
       & (_GEN_6 | ~_GEN_23 & (_GEN_13 | ~_GEN_12 & (_GEN_11 | ~_GEN_21))))
      ? io_inst[14:10]
      : io_inst[4:0];
  wire [3:0][4:0]   _GEN_25 = {{io_inst[4:0]}, {io_inst[9:5]}, {5'h1}, {io_inst[4:0]}};
  wire [15:0][31:0] _GEN_26 =
    {{32'h6},
     {32'h6},
     {32'h6},
     {32'h6},
     {{{18{io_inst[21]}}, io_inst[21:10], 2'h0}},
     {32'h6},
     {32'h6},
     {32'h40},
     {{18'h0, io_inst[23:10]}},
     {{{4{io_inst[9]}}, io_inst[9:0], io_inst[25:10], 2'h0}},
     {{io_inst[24:5], 12'h0}},
     {{{14{io_inst[25]}}, io_inst[25:10], 2'h0}},
     {{{20{io_inst[21]}}, io_inst[21:10]}},
     {{20'h0, io_inst[21:10]}},
     {{27'h0, io_inst[14:10]}},
     {32'h0}};
  assign io_rj =
    ~_GEN_10
    & (_GEN_8 | ~_GEN_7
       & (_GEN_6 | ~(_control_signal_T_65 | _control_signal_T_67)
          & (_control_signal_T_69 | ~_GEN_4
             & (_control_signal_T_79 | _control_signal_T_81 | _control_signal_T_83
                | _control_signal_T_85 | _control_signal_T_87 | _control_signal_T_89
                | _GEN_2 | ~_GEN_1 & (_GEN_0 | _control_signal_T_167)))))
      ? io_inst[9:5]
      : 5'h0;
  assign io_rk =
    ~_GEN_10
    & (_GEN_8
       | ~(_control_signal_T_43 | _control_signal_T_45 | _control_signal_T_47
           | _control_signal_T_49 | _control_signal_T_51 | _control_signal_T_53
           | _control_signal_T_55 | _control_signal_T_57 | _control_signal_T_59
           | _control_signal_T_61 | _control_signal_T_63 | _control_signal_T_65)
       & (_GEN_14 | ~(_control_signal_T_71 | _control_signal_T_73 | _GEN_13)
          & (_GEN_12 | ~_GEN_11 & (_GEN_0 | _control_signal_T_167))))
      ? _io_rk_T_3
      : 5'h0;
  assign io_rd = _GEN_25[control_signal_10];
  assign io_rd_valid =
    (_GEN_18 | ~_GEN_7
     & (_control_signal_T_47 | _control_signal_T_49 | _control_signal_T_51
        | _control_signal_T_53 | _control_signal_T_55 | _control_signal_T_57
        | _control_signal_T_59 | _control_signal_T_61 | _control_signal_T_63 | _GEN_16
        | ~_GEN_15
        & (_GEN_13 | ~_GEN_12
           & (_GEN_2 | ~_control_signal_T_97 & _control_signal_T_338))))
    & (|_GEN_25[control_signal_10]);
  assign io_imm = _GEN_26[control_signal_11];
  assign io_alu_op = {1'h0, control_signal_3};
  assign io_alu_rs1_sel =
    ~(_control_signal_T_1 | _control_signal_T_3 | _control_signal_T_5
      | _control_signal_T_7 | _control_signal_T_9 | _control_signal_T_11
      | _control_signal_T_13 | _control_signal_T_15 | _control_signal_T_17
      | _control_signal_T_19 | _control_signal_T_21 | _control_signal_T_23
      | _control_signal_T_25 | _control_signal_T_27 | _control_signal_T_29
      | _control_signal_T_31 | _control_signal_T_33 | _control_signal_T_35
      | _control_signal_T_37 | _control_signal_T_39 | _control_signal_T_41
      | _control_signal_T_43 | _control_signal_T_45 | _control_signal_T_47
      | _control_signal_T_49 | _control_signal_T_51 | _control_signal_T_53
      | _control_signal_T_55 | _control_signal_T_57 | _control_signal_T_59
      | _control_signal_T_61 | _control_signal_T_63 | _control_signal_T_65
      | _control_signal_T_67 | _control_signal_T_69 | _control_signal_T_71
      | _control_signal_T_73 | _control_signal_T_75)
    & (_control_signal_T_77 | ~_GEN_19
       & (_control_signal_T_95 | ~_control_signal_T_97 & _control_signal_T_338));
  assign io_alu_rs2_sel = _control_signal_T_1 ? 2'h1 : _control_signal_T_441;
  assign io_br_type =
    _control_signal_T_1 | _control_signal_T_3 | _control_signal_T_5 | _control_signal_T_7
    | _control_signal_T_9 | _control_signal_T_11 | _control_signal_T_13
    | _control_signal_T_15 | _control_signal_T_17 | _control_signal_T_19
    | _control_signal_T_21 | _control_signal_T_23 | _control_signal_T_25
    | _control_signal_T_27 | _control_signal_T_29 | _control_signal_T_31
    | _control_signal_T_33 | _control_signal_T_35 | _control_signal_T_37
    | _control_signal_T_39 | _control_signal_T_41 | _GEN_20
      ? 4'h0
      : _control_signal_T_450;
  assign io_mem_type =
    _control_signal_T_1 | _control_signal_T_3 | _control_signal_T_5 | _control_signal_T_7
    | _control_signal_T_9 | _control_signal_T_11 | _control_signal_T_13
    | _control_signal_T_15 | _control_signal_T_17 | _control_signal_T_19
    | _control_signal_T_21 | _control_signal_T_23 | _control_signal_T_25
    | _control_signal_T_27 | _control_signal_T_29 | _control_signal_T_31
    | _control_signal_T_33 | _control_signal_T_35 | _control_signal_T_37
    | _control_signal_T_39 | _control_signal_T_41 | _control_signal_T_43
    | _control_signal_T_45 | _control_signal_T_47 | _control_signal_T_49
    | _control_signal_T_51 | _control_signal_T_53 | _control_signal_T_55
    | _control_signal_T_57 | _control_signal_T_59 | _control_signal_T_61
    | _control_signal_T_63 | _control_signal_T_65 | _control_signal_T_67
    | _control_signal_T_69 | _GEN_4
      ? 5'h0
      : _control_signal_T_513;
  assign io_priv_vec = _control_signal_T_1 ? 13'h1 : _control_signal_T_826;
  assign io_fu_id = _control_signal_T_1 ? 3'h2 : _control_signal_T_606;
  assign io_exception = _GEN_18 ? 8'h0 : _control_signal_T_861;
endmodule

