// Generated by CIRCT firtool-1.62.0
module ID_RN_Reg(
  input         clock,
                reset,
                io_flush,
                io_stall,
  input  [31:0] io_insts_pack_ID_pc_0,
                io_insts_pack_ID_pc_1,
  input         io_insts_pack_ID_inst_valid_0,
                io_insts_pack_ID_inst_valid_1,
                io_insts_pack_ID_predict_jump_0,
                io_insts_pack_ID_predict_jump_1,
  input  [31:0] io_insts_pack_ID_pred_npc_0,
                io_insts_pack_ID_pred_npc_1,
  input  [7:0]  io_insts_pack_ID_exception_0,
                io_insts_pack_ID_exception_1,
  input  [4:0]  io_insts_pack_ID_rj_0,
                io_insts_pack_ID_rj_1,
                io_insts_pack_ID_rk_0,
                io_insts_pack_ID_rk_1,
                io_insts_pack_ID_rd_0,
                io_insts_pack_ID_rd_1,
  input         io_insts_pack_ID_rd_valid_0,
                io_insts_pack_ID_rd_valid_1,
  input  [31:0] io_insts_pack_ID_imm_0,
                io_insts_pack_ID_imm_1,
  input  [3:0]  io_insts_pack_ID_alu_op_0,
                io_insts_pack_ID_alu_op_1,
  input         io_insts_pack_ID_alu_rs1_sel_0,
                io_insts_pack_ID_alu_rs1_sel_1,
  input  [1:0]  io_insts_pack_ID_alu_rs2_sel_0,
                io_insts_pack_ID_alu_rs2_sel_1,
  input  [3:0]  io_insts_pack_ID_br_type_0,
                io_insts_pack_ID_br_type_1,
  input  [4:0]  io_insts_pack_ID_mem_type_0,
                io_insts_pack_ID_mem_type_1,
  input  [12:0] io_insts_pack_ID_priv_vec_0,
                io_insts_pack_ID_priv_vec_1,
  input  [2:0]  io_insts_pack_ID_fu_id_0,
                io_insts_pack_ID_fu_id_1,
  input  [5:0]  io_alloc_preg_ID_0,
                io_alloc_preg_ID_1,
  output [31:0] io_insts_pack_RN_pc_0,
                io_insts_pack_RN_pc_1,
  output        io_insts_pack_RN_inst_valid_0,
                io_insts_pack_RN_inst_valid_1,
                io_insts_pack_RN_predict_jump_0,
                io_insts_pack_RN_predict_jump_1,
  output [31:0] io_insts_pack_RN_pred_npc_0,
                io_insts_pack_RN_pred_npc_1,
  output [7:0]  io_insts_pack_RN_exception_0,
                io_insts_pack_RN_exception_1,
  output [4:0]  io_insts_pack_RN_rj_0,
                io_insts_pack_RN_rj_1,
                io_insts_pack_RN_rk_0,
                io_insts_pack_RN_rk_1,
                io_insts_pack_RN_rd_0,
                io_insts_pack_RN_rd_1,
  output        io_insts_pack_RN_rd_valid_0,
                io_insts_pack_RN_rd_valid_1,
  output [31:0] io_insts_pack_RN_imm_0,
                io_insts_pack_RN_imm_1,
  output [3:0]  io_insts_pack_RN_alu_op_0,
                io_insts_pack_RN_alu_op_1,
  output        io_insts_pack_RN_alu_rs1_sel_0,
                io_insts_pack_RN_alu_rs1_sel_1,
  output [1:0]  io_insts_pack_RN_alu_rs2_sel_0,
                io_insts_pack_RN_alu_rs2_sel_1,
  output [3:0]  io_insts_pack_RN_br_type_0,
                io_insts_pack_RN_br_type_1,
  output [4:0]  io_insts_pack_RN_mem_type_0,
                io_insts_pack_RN_mem_type_1,
  output [12:0] io_insts_pack_RN_priv_vec_0,
                io_insts_pack_RN_priv_vec_1,
  output [2:0]  io_insts_pack_RN_fu_id_0,
                io_insts_pack_RN_fu_id_1,
  output [5:0]  io_alloc_preg_RN_0,
                io_alloc_preg_RN_1
);

  reg  [31:0] insts_pack_reg_pc_0;
  reg  [31:0] insts_pack_reg_pc_1;
  reg         insts_pack_reg_inst_valid_0;
  reg         insts_pack_reg_inst_valid_1;
  reg         insts_pack_reg_predict_jump_0;
  reg         insts_pack_reg_predict_jump_1;
  reg  [31:0] insts_pack_reg_pred_npc_0;
  reg  [31:0] insts_pack_reg_pred_npc_1;
  reg  [7:0]  insts_pack_reg_exception_0;
  reg  [7:0]  insts_pack_reg_exception_1;
  reg  [4:0]  insts_pack_reg_rj_0;
  reg  [4:0]  insts_pack_reg_rj_1;
  reg  [4:0]  insts_pack_reg_rk_0;
  reg  [4:0]  insts_pack_reg_rk_1;
  reg  [4:0]  insts_pack_reg_rd_0;
  reg  [4:0]  insts_pack_reg_rd_1;
  reg         insts_pack_reg_rd_valid_0;
  reg         insts_pack_reg_rd_valid_1;
  reg  [31:0] insts_pack_reg_imm_0;
  reg  [31:0] insts_pack_reg_imm_1;
  reg  [3:0]  insts_pack_reg_alu_op_0;
  reg  [3:0]  insts_pack_reg_alu_op_1;
  reg         insts_pack_reg_alu_rs1_sel_0;
  reg         insts_pack_reg_alu_rs1_sel_1;
  reg  [1:0]  insts_pack_reg_alu_rs2_sel_0;
  reg  [1:0]  insts_pack_reg_alu_rs2_sel_1;
  reg  [3:0]  insts_pack_reg_br_type_0;
  reg  [3:0]  insts_pack_reg_br_type_1;
  reg  [4:0]  insts_pack_reg_mem_type_0;
  reg  [4:0]  insts_pack_reg_mem_type_1;
  reg  [12:0] insts_pack_reg_priv_vec_0;
  reg  [12:0] insts_pack_reg_priv_vec_1;
  reg  [2:0]  insts_pack_reg_fu_id_0;
  reg  [2:0]  insts_pack_reg_fu_id_1;
  reg  [5:0]  alloc_preg_reg_0;
  reg  [5:0]  alloc_preg_reg_1;
  wire        _GEN =
    io_stall ? insts_pack_reg_inst_valid_0 : io_insts_pack_ID_inst_valid_0;
  wire        _GEN_0 =
    io_stall ? insts_pack_reg_inst_valid_1 : io_insts_pack_ID_inst_valid_1;
  wire        _GEN_1 =
    io_stall ? insts_pack_reg_predict_jump_0 : io_insts_pack_ID_predict_jump_0;
  wire        _GEN_2 =
    io_stall ? insts_pack_reg_predict_jump_1 : io_insts_pack_ID_predict_jump_1;
  wire        _GEN_3 = io_stall ? insts_pack_reg_rd_valid_0 : io_insts_pack_ID_rd_valid_0;
  wire        _GEN_4 = io_stall ? insts_pack_reg_rd_valid_1 : io_insts_pack_ID_rd_valid_1;
  wire        _GEN_5 =
    io_stall ? insts_pack_reg_alu_rs1_sel_0 : io_insts_pack_ID_alu_rs1_sel_0;
  wire        _GEN_6 =
    io_stall ? insts_pack_reg_alu_rs1_sel_1 : io_insts_pack_ID_alu_rs1_sel_1;
  always @(posedge clock) begin
    if (reset) begin
      insts_pack_reg_pc_0 <= 32'h0;
      insts_pack_reg_pc_1 <= 32'h0;
      insts_pack_reg_inst_valid_0 <= 1'h0;
      insts_pack_reg_inst_valid_1 <= 1'h0;
      insts_pack_reg_predict_jump_0 <= 1'h0;
      insts_pack_reg_predict_jump_1 <= 1'h0;
      insts_pack_reg_pred_npc_0 <= 32'h0;
      insts_pack_reg_pred_npc_1 <= 32'h0;
      insts_pack_reg_exception_0 <= 8'h0;
      insts_pack_reg_exception_1 <= 8'h0;
      insts_pack_reg_rj_0 <= 5'h0;
      insts_pack_reg_rj_1 <= 5'h0;
      insts_pack_reg_rk_0 <= 5'h0;
      insts_pack_reg_rk_1 <= 5'h0;
      insts_pack_reg_rd_0 <= 5'h0;
      insts_pack_reg_rd_1 <= 5'h0;
      insts_pack_reg_rd_valid_0 <= 1'h0;
      insts_pack_reg_rd_valid_1 <= 1'h0;
      insts_pack_reg_imm_0 <= 32'h0;
      insts_pack_reg_imm_1 <= 32'h0;
      insts_pack_reg_alu_op_0 <= 4'h0;
      insts_pack_reg_alu_op_1 <= 4'h0;
      insts_pack_reg_alu_rs1_sel_0 <= 1'h0;
      insts_pack_reg_alu_rs1_sel_1 <= 1'h0;
      insts_pack_reg_alu_rs2_sel_0 <= 2'h0;
      insts_pack_reg_alu_rs2_sel_1 <= 2'h0;
      insts_pack_reg_br_type_0 <= 4'h0;
      insts_pack_reg_br_type_1 <= 4'h0;
      insts_pack_reg_mem_type_0 <= 5'h0;
      insts_pack_reg_mem_type_1 <= 5'h0;
      insts_pack_reg_priv_vec_0 <= 13'h0;
      insts_pack_reg_priv_vec_1 <= 13'h0;
      insts_pack_reg_fu_id_0 <= 3'h0;
      insts_pack_reg_fu_id_1 <= 3'h0;
      alloc_preg_reg_0 <= 6'h0;
      alloc_preg_reg_1 <= 6'h0;
    end
    else begin
      if (io_flush) begin
        insts_pack_reg_pc_0 <= 32'h0;
        insts_pack_reg_pc_1 <= 32'h0;
        insts_pack_reg_pred_npc_0 <= 32'h0;
        insts_pack_reg_pred_npc_1 <= 32'h0;
        insts_pack_reg_exception_0 <= 8'h0;
        insts_pack_reg_exception_1 <= 8'h0;
        insts_pack_reg_rj_0 <= 5'h0;
        insts_pack_reg_rj_1 <= 5'h0;
        insts_pack_reg_rk_0 <= 5'h0;
        insts_pack_reg_rk_1 <= 5'h0;
        insts_pack_reg_rd_0 <= 5'h0;
        insts_pack_reg_rd_1 <= 5'h0;
        insts_pack_reg_imm_0 <= 32'h0;
        insts_pack_reg_imm_1 <= 32'h0;
        insts_pack_reg_alu_op_0 <= 4'h0;
        insts_pack_reg_alu_op_1 <= 4'h0;
        insts_pack_reg_alu_rs2_sel_0 <= 2'h0;
        insts_pack_reg_alu_rs2_sel_1 <= 2'h0;
        insts_pack_reg_br_type_0 <= 4'h0;
        insts_pack_reg_br_type_1 <= 4'h0;
        insts_pack_reg_mem_type_0 <= 5'h0;
        insts_pack_reg_mem_type_1 <= 5'h0;
        insts_pack_reg_priv_vec_0 <= 13'h0;
        insts_pack_reg_priv_vec_1 <= 13'h0;
        insts_pack_reg_fu_id_0 <= 3'h0;
        insts_pack_reg_fu_id_1 <= 3'h0;
        alloc_preg_reg_0 <= 6'h0;
        alloc_preg_reg_1 <= 6'h0;
      end
      else if (io_stall) begin
      end
      else begin
        insts_pack_reg_pc_0 <= io_insts_pack_ID_pc_0;
        insts_pack_reg_pc_1 <= io_insts_pack_ID_pc_1;
        insts_pack_reg_pred_npc_0 <= io_insts_pack_ID_pred_npc_0;
        insts_pack_reg_pred_npc_1 <= io_insts_pack_ID_pred_npc_1;
        insts_pack_reg_exception_0 <= io_insts_pack_ID_exception_0;
        insts_pack_reg_exception_1 <= io_insts_pack_ID_exception_1;
        insts_pack_reg_rj_0 <= io_insts_pack_ID_rj_0;
        insts_pack_reg_rj_1 <= io_insts_pack_ID_rj_1;
        insts_pack_reg_rk_0 <= io_insts_pack_ID_rk_0;
        insts_pack_reg_rk_1 <= io_insts_pack_ID_rk_1;
        insts_pack_reg_rd_0 <= io_insts_pack_ID_rd_0;
        insts_pack_reg_rd_1 <= io_insts_pack_ID_rd_1;
        insts_pack_reg_imm_0 <= io_insts_pack_ID_imm_0;
        insts_pack_reg_imm_1 <= io_insts_pack_ID_imm_1;
        insts_pack_reg_alu_op_0 <= io_insts_pack_ID_alu_op_0;
        insts_pack_reg_alu_op_1 <= io_insts_pack_ID_alu_op_1;
        insts_pack_reg_alu_rs2_sel_0 <= io_insts_pack_ID_alu_rs2_sel_0;
        insts_pack_reg_alu_rs2_sel_1 <= io_insts_pack_ID_alu_rs2_sel_1;
        insts_pack_reg_br_type_0 <= io_insts_pack_ID_br_type_0;
        insts_pack_reg_br_type_1 <= io_insts_pack_ID_br_type_1;
        insts_pack_reg_mem_type_0 <= io_insts_pack_ID_mem_type_0;
        insts_pack_reg_mem_type_1 <= io_insts_pack_ID_mem_type_1;
        insts_pack_reg_priv_vec_0 <= io_insts_pack_ID_priv_vec_0;
        insts_pack_reg_priv_vec_1 <= io_insts_pack_ID_priv_vec_1;
        insts_pack_reg_fu_id_0 <= io_insts_pack_ID_fu_id_0;
        insts_pack_reg_fu_id_1 <= io_insts_pack_ID_fu_id_1;
        alloc_preg_reg_0 <= io_alloc_preg_ID_0;
        alloc_preg_reg_1 <= io_alloc_preg_ID_1;
      end
      insts_pack_reg_inst_valid_0 <= ~io_flush & _GEN;
      insts_pack_reg_inst_valid_1 <= ~io_flush & _GEN_0;
      insts_pack_reg_predict_jump_0 <= ~io_flush & _GEN_1;
      insts_pack_reg_predict_jump_1 <= ~io_flush & _GEN_2;
      insts_pack_reg_rd_valid_0 <= ~io_flush & _GEN_3;
      insts_pack_reg_rd_valid_1 <= ~io_flush & _GEN_4;
      insts_pack_reg_alu_rs1_sel_0 <= ~io_flush & _GEN_5;
      insts_pack_reg_alu_rs1_sel_1 <= ~io_flush & _GEN_6;
    end
  end // always @(posedge)
  assign io_insts_pack_RN_pc_0 = insts_pack_reg_pc_0;
  assign io_insts_pack_RN_pc_1 = insts_pack_reg_pc_1;
  assign io_insts_pack_RN_inst_valid_0 = insts_pack_reg_inst_valid_0;
  assign io_insts_pack_RN_inst_valid_1 = insts_pack_reg_inst_valid_1;
  assign io_insts_pack_RN_predict_jump_0 = insts_pack_reg_predict_jump_0;
  assign io_insts_pack_RN_predict_jump_1 = insts_pack_reg_predict_jump_1;
  assign io_insts_pack_RN_pred_npc_0 = insts_pack_reg_pred_npc_0;
  assign io_insts_pack_RN_pred_npc_1 = insts_pack_reg_pred_npc_1;
  assign io_insts_pack_RN_exception_0 = insts_pack_reg_exception_0;
  assign io_insts_pack_RN_exception_1 = insts_pack_reg_exception_1;
  assign io_insts_pack_RN_rj_0 = insts_pack_reg_rj_0;
  assign io_insts_pack_RN_rj_1 = insts_pack_reg_rj_1;
  assign io_insts_pack_RN_rk_0 = insts_pack_reg_rk_0;
  assign io_insts_pack_RN_rk_1 = insts_pack_reg_rk_1;
  assign io_insts_pack_RN_rd_0 = insts_pack_reg_rd_0;
  assign io_insts_pack_RN_rd_1 = insts_pack_reg_rd_1;
  assign io_insts_pack_RN_rd_valid_0 = insts_pack_reg_rd_valid_0;
  assign io_insts_pack_RN_rd_valid_1 = insts_pack_reg_rd_valid_1;
  assign io_insts_pack_RN_imm_0 = insts_pack_reg_imm_0;
  assign io_insts_pack_RN_imm_1 = insts_pack_reg_imm_1;
  assign io_insts_pack_RN_alu_op_0 = insts_pack_reg_alu_op_0;
  assign io_insts_pack_RN_alu_op_1 = insts_pack_reg_alu_op_1;
  assign io_insts_pack_RN_alu_rs1_sel_0 = insts_pack_reg_alu_rs1_sel_0;
  assign io_insts_pack_RN_alu_rs1_sel_1 = insts_pack_reg_alu_rs1_sel_1;
  assign io_insts_pack_RN_alu_rs2_sel_0 = insts_pack_reg_alu_rs2_sel_0;
  assign io_insts_pack_RN_alu_rs2_sel_1 = insts_pack_reg_alu_rs2_sel_1;
  assign io_insts_pack_RN_br_type_0 = insts_pack_reg_br_type_0;
  assign io_insts_pack_RN_br_type_1 = insts_pack_reg_br_type_1;
  assign io_insts_pack_RN_mem_type_0 = insts_pack_reg_mem_type_0;
  assign io_insts_pack_RN_mem_type_1 = insts_pack_reg_mem_type_1;
  assign io_insts_pack_RN_priv_vec_0 = insts_pack_reg_priv_vec_0;
  assign io_insts_pack_RN_priv_vec_1 = insts_pack_reg_priv_vec_1;
  assign io_insts_pack_RN_fu_id_0 = insts_pack_reg_fu_id_0;
  assign io_insts_pack_RN_fu_id_1 = insts_pack_reg_fu_id_1;
  assign io_alloc_preg_RN_0 = alloc_preg_reg_0;
  assign io_alloc_preg_RN_1 = alloc_preg_reg_1;
endmodule

