// Generated by CIRCT firtool-1.62.0
module Order_Issue_Queue(
  input         clock,
                reset,
                io_insts_disp_valid_0,
                io_insts_disp_valid_1,
  input  [5:0]  io_insts_dispatch_prj_0,
                io_insts_dispatch_prj_1,
                io_insts_dispatch_prk_0,
                io_insts_dispatch_prk_1,
  input         io_insts_dispatch_rd_valid_0,
                io_insts_dispatch_rd_valid_1,
  input  [5:0]  io_insts_dispatch_prd_0,
                io_insts_dispatch_prd_1,
  input  [31:0] io_insts_dispatch_imm_0,
                io_insts_dispatch_imm_1,
  input  [4:0]  io_insts_dispatch_rob_index_0,
                io_insts_dispatch_rob_index_1,
  input  [9:0]  io_insts_dispatch_priv_vec_0,
                io_insts_dispatch_priv_vec_1,
  input  [3:0]  io_insts_dispatch_alu_op_0,
                io_insts_dispatch_alu_op_1,
  input         io_prj_ready_0,
                io_prj_ready_1,
                io_prk_ready_0,
                io_prk_ready_1,
  input  [5:0]  io_wake_preg_0,
                io_wake_preg_1,
                io_wake_preg_2,
                io_wake_preg_3,
                io_ld_mem_prd,
  input         io_issue_ack,
  output [5:0]  io_insts_issue_inst_prj,
                io_insts_issue_inst_prk,
  output        io_insts_issue_inst_rd_valid,
  output [5:0]  io_insts_issue_inst_prd,
  output [31:0] io_insts_issue_inst_imm,
  output [4:0]  io_insts_issue_inst_rob_index,
  output [9:0]  io_insts_issue_inst_priv_vec,
  output [3:0]  io_insts_issue_inst_alu_op,
  output        io_issue_req,
                io_full,
  input         io_stall,
                io_flush,
                io_dcache_miss
);

  reg  [5:0]  queue_inst_prj_0;
  reg  [5:0]  queue_inst_prj_1;
  reg  [5:0]  queue_inst_prj_2;
  reg  [5:0]  queue_inst_prj_3;
  reg  [5:0]  queue_inst_prk_0;
  reg  [5:0]  queue_inst_prk_1;
  reg  [5:0]  queue_inst_prk_2;
  reg  [5:0]  queue_inst_prk_3;
  reg         queue_inst_rd_valid_0;
  reg         queue_inst_rd_valid_1;
  reg         queue_inst_rd_valid_2;
  reg         queue_inst_rd_valid_3;
  reg  [5:0]  queue_inst_prd_0;
  reg  [5:0]  queue_inst_prd_1;
  reg  [5:0]  queue_inst_prd_2;
  reg  [5:0]  queue_inst_prd_3;
  reg  [31:0] queue_inst_imm_0;
  reg  [31:0] queue_inst_imm_1;
  reg  [31:0] queue_inst_imm_2;
  reg  [31:0] queue_inst_imm_3;
  reg  [4:0]  queue_inst_rob_index_0;
  reg  [4:0]  queue_inst_rob_index_1;
  reg  [4:0]  queue_inst_rob_index_2;
  reg  [4:0]  queue_inst_rob_index_3;
  reg  [9:0]  queue_inst_priv_vec_0;
  reg  [9:0]  queue_inst_priv_vec_1;
  reg  [9:0]  queue_inst_priv_vec_2;
  reg  [9:0]  queue_inst_priv_vec_3;
  reg  [3:0]  queue_inst_alu_op_0;
  reg  [3:0]  queue_inst_alu_op_1;
  reg  [3:0]  queue_inst_alu_op_2;
  reg  [3:0]  queue_inst_alu_op_3;
  reg         queue_prj_waked_0;
  reg         queue_prj_waked_1;
  reg         queue_prj_waked_2;
  reg         queue_prj_waked_3;
  reg         queue_prk_waked_0;
  reg         queue_prk_waked_1;
  reg         queue_prk_waked_2;
  reg         queue_prk_waked_3;
  reg         queue_prj_wake_by_ld_0;
  reg         queue_prj_wake_by_ld_1;
  reg         queue_prj_wake_by_ld_2;
  reg         queue_prj_wake_by_ld_3;
  reg         queue_prk_wake_by_ld_0;
  reg         queue_prk_wake_by_ld_1;
  reg         queue_prk_wake_by_ld_2;
  reg         queue_prk_wake_by_ld_3;
  reg  [2:0]  num;
  reg  [3:0]  qvalid;
  wire [1:0]  ins_num = 2'({1'h0, io_insts_disp_valid_0} + {1'h0, io_insts_disp_valid_1});
  wire [2:0]  _num_pop_T_1 = 3'(num - {2'h0, io_issue_ack});
  wire        index = 1'(1'h0 - _num_pop_T_1[0]);
  wire        _GEN = io_insts_disp_valid_0 & ~io_insts_disp_valid_1;
  wire        _GEN_0 = _GEN | index;
  wire [5:0]  _GEN_1 = _GEN_0 ? io_insts_dispatch_prj_1 : io_insts_dispatch_prj_0;
  wire [5:0]  _queue_next_T_inst_prj = io_issue_ack ? queue_inst_prj_1 : queue_inst_prj_0;
  wire [5:0]  queue_next_inst_prj = qvalid[0] ? _queue_next_T_inst_prj : _GEN_1;
  wire [5:0]  _GEN_2 = _GEN_0 ? io_insts_dispatch_prk_1 : io_insts_dispatch_prk_0;
  wire [5:0]  _queue_next_T_inst_prk = io_issue_ack ? queue_inst_prk_1 : queue_inst_prk_0;
  wire [5:0]  queue_next_inst_prk = qvalid[0] ? _queue_next_T_inst_prk : _GEN_2;
  wire [5:0]  _queue_0_prj_wake_by_ld_T = queue_next_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_0_prk_wake_by_ld_T = queue_next_inst_prk ^ io_wake_preg_3;
  wire        _index_T_2 = 1'(1'h1 - _num_pop_T_1[0]);
  wire        _GEN_3 = _GEN | _index_T_2;
  wire [5:0]  _GEN_4 = _GEN_3 ? io_insts_dispatch_prj_1 : io_insts_dispatch_prj_0;
  wire [5:0]  _queue_next_T_1_inst_prj =
    io_issue_ack ? queue_inst_prj_2 : queue_inst_prj_1;
  wire [5:0]  queue_next_1_inst_prj = qvalid[1] ? _queue_next_T_1_inst_prj : _GEN_4;
  wire [5:0]  _GEN_5 = _GEN_3 ? io_insts_dispatch_prk_1 : io_insts_dispatch_prk_0;
  wire [5:0]  _queue_next_T_1_inst_prk =
    io_issue_ack ? queue_inst_prk_2 : queue_inst_prk_1;
  wire [5:0]  queue_next_1_inst_prk = qvalid[1] ? _queue_next_T_1_inst_prk : _GEN_5;
  wire [5:0]  _queue_1_prj_wake_by_ld_T = queue_next_1_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_1_prk_wake_by_ld_T = queue_next_1_inst_prk ^ io_wake_preg_3;
  wire        _index_T_4 = 1'(1'h0 - _num_pop_T_1[0]);
  wire        _GEN_6 = _GEN | _index_T_4;
  wire [5:0]  _GEN_7 = _GEN_6 ? io_insts_dispatch_prj_1 : io_insts_dispatch_prj_0;
  wire [5:0]  _queue_next_T_2_inst_prj =
    io_issue_ack ? queue_inst_prj_3 : queue_inst_prj_2;
  wire [5:0]  queue_next_2_inst_prj = qvalid[2] ? _queue_next_T_2_inst_prj : _GEN_7;
  wire [5:0]  _GEN_8 = _GEN_6 ? io_insts_dispatch_prk_1 : io_insts_dispatch_prk_0;
  wire [5:0]  _queue_next_T_2_inst_prk =
    io_issue_ack ? queue_inst_prk_3 : queue_inst_prk_2;
  wire [5:0]  queue_next_2_inst_prk = qvalid[2] ? _queue_next_T_2_inst_prk : _GEN_8;
  wire [5:0]  _queue_2_prj_wake_by_ld_T = queue_next_2_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_2_prk_wake_by_ld_T = queue_next_2_inst_prk ^ io_wake_preg_3;
  wire        _index_T_6 = 1'(1'h1 - _num_pop_T_1[0]);
  wire        _GEN_9 = _GEN | _index_T_6;
  wire [5:0]  _GEN_10 = _GEN_9 ? io_insts_dispatch_prj_1 : io_insts_dispatch_prj_0;
  wire [5:0]  queue_next_3_inst_prj = qvalid[3] ? queue_inst_prj_3 : _GEN_10;
  wire [5:0]  _GEN_11 = _GEN_9 ? io_insts_dispatch_prk_1 : io_insts_dispatch_prk_0;
  wire [5:0]  queue_next_3_inst_prk = qvalid[3] ? queue_inst_prk_3 : _GEN_11;
  wire [5:0]  _queue_3_prj_wake_by_ld_T = queue_next_3_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_3_prk_wake_by_ld_T = queue_next_3_inst_prk ^ io_wake_preg_3;
  wire        _GEN_12 = _GEN_0 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_prj_waked =
    io_issue_ack ? queue_prj_waked_1 : queue_prj_waked_0;
  wire        queue_next_prj_waked = qvalid[0] ? _queue_next_T_prj_waked : _GEN_12;
  wire        _GEN_13 = _GEN_3 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_1_prj_waked =
    io_issue_ack ? queue_prj_waked_2 : queue_prj_waked_1;
  wire        queue_next_1_prj_waked = qvalid[1] ? _queue_next_T_1_prj_waked : _GEN_13;
  wire        _GEN_14 = _GEN_6 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_2_prj_waked =
    io_issue_ack ? queue_prj_waked_3 : queue_prj_waked_2;
  wire        queue_next_2_prj_waked = qvalid[2] ? _queue_next_T_2_prj_waked : _GEN_14;
  wire        _GEN_15 = _GEN_9 ? io_prj_ready_1 : io_prj_ready_0;
  wire        queue_next_3_prj_waked = qvalid[3] ? queue_prj_waked_3 : _GEN_15;
  wire        _GEN_16 = _GEN_0 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_prk_waked =
    io_issue_ack ? queue_prk_waked_1 : queue_prk_waked_0;
  wire        queue_next_prk_waked = qvalid[0] ? _queue_next_T_prk_waked : _GEN_16;
  wire        _GEN_17 = _GEN_3 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_1_prk_waked =
    io_issue_ack ? queue_prk_waked_2 : queue_prk_waked_1;
  wire        queue_next_1_prk_waked = qvalid[1] ? _queue_next_T_1_prk_waked : _GEN_17;
  wire        _GEN_18 = _GEN_6 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_2_prk_waked =
    io_issue_ack ? queue_prk_waked_3 : queue_prk_waked_2;
  wire        queue_next_2_prk_waked = qvalid[2] ? _queue_next_T_2_prk_waked : _GEN_18;
  wire        _GEN_19 = _GEN_9 ? io_prk_ready_1 : io_prk_ready_0;
  wire        queue_next_3_prk_waked = qvalid[3] ? queue_prk_waked_3 : _GEN_19;
  wire [5:0]  _GEN_20 = index ? io_insts_dispatch_prj_1 : io_insts_dispatch_prj_0;
  wire        _GEN_21 =
    _GEN
      ? (io_insts_dispatch_prj_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_20 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_prj_wake_by_ld =
    io_issue_ack ? queue_prj_wake_by_ld_1 : queue_prj_wake_by_ld_0;
  wire        queue_next_prj_wake_by_ld =
    qvalid[0] ? _queue_next_T_prj_wake_by_ld : _GEN_21;
  wire [5:0]  _GEN_22 = _index_T_2 ? io_insts_dispatch_prj_1 : io_insts_dispatch_prj_0;
  wire        _GEN_23 =
    _GEN
      ? (io_insts_dispatch_prj_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_22 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_1_prj_wake_by_ld =
    io_issue_ack ? queue_prj_wake_by_ld_2 : queue_prj_wake_by_ld_1;
  wire        queue_next_1_prj_wake_by_ld =
    qvalid[1] ? _queue_next_T_1_prj_wake_by_ld : _GEN_23;
  wire [5:0]  _GEN_24 = _index_T_4 ? io_insts_dispatch_prj_1 : io_insts_dispatch_prj_0;
  wire        _GEN_25 =
    _GEN
      ? (io_insts_dispatch_prj_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_24 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_2_prj_wake_by_ld =
    io_issue_ack ? queue_prj_wake_by_ld_3 : queue_prj_wake_by_ld_2;
  wire        queue_next_2_prj_wake_by_ld =
    qvalid[2] ? _queue_next_T_2_prj_wake_by_ld : _GEN_25;
  wire [5:0]  _GEN_26 = _index_T_6 ? io_insts_dispatch_prj_1 : io_insts_dispatch_prj_0;
  wire        _GEN_27 =
    _GEN
      ? (io_insts_dispatch_prj_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_26 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        queue_next_3_prj_wake_by_ld = qvalid[3] ? queue_prj_wake_by_ld_3 : _GEN_27;
  wire [5:0]  _GEN_28 = index ? io_insts_dispatch_prk_1 : io_insts_dispatch_prk_0;
  wire        _GEN_29 =
    _GEN
      ? (io_insts_dispatch_prk_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_28 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_prk_wake_by_ld =
    io_issue_ack ? queue_prk_wake_by_ld_1 : queue_prk_wake_by_ld_0;
  wire        queue_next_prk_wake_by_ld =
    qvalid[0] ? _queue_next_T_prk_wake_by_ld : _GEN_29;
  wire [5:0]  _GEN_30 = _index_T_2 ? io_insts_dispatch_prk_1 : io_insts_dispatch_prk_0;
  wire        _GEN_31 =
    _GEN
      ? (io_insts_dispatch_prk_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_30 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_1_prk_wake_by_ld =
    io_issue_ack ? queue_prk_wake_by_ld_2 : queue_prk_wake_by_ld_1;
  wire        queue_next_1_prk_wake_by_ld =
    qvalid[1] ? _queue_next_T_1_prk_wake_by_ld : _GEN_31;
  wire [5:0]  _GEN_32 = _index_T_4 ? io_insts_dispatch_prk_1 : io_insts_dispatch_prk_0;
  wire        _GEN_33 =
    _GEN
      ? (io_insts_dispatch_prk_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_32 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_2_prk_wake_by_ld =
    io_issue_ack ? queue_prk_wake_by_ld_3 : queue_prk_wake_by_ld_2;
  wire        queue_next_2_prk_wake_by_ld =
    qvalid[2] ? _queue_next_T_2_prk_wake_by_ld : _GEN_33;
  wire [5:0]  _GEN_34 = _index_T_6 ? io_insts_dispatch_prk_1 : io_insts_dispatch_prk_0;
  wire        _GEN_35 =
    _GEN
      ? (io_insts_dispatch_prk_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd)
      : (_GEN_34 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        queue_next_3_prk_wake_by_ld = qvalid[3] ? queue_prk_wake_by_ld_3 : _GEN_35;
  always @(posedge clock) begin
    if (reset) begin
      queue_inst_prj_0 <= 6'h0;
      queue_inst_prj_1 <= 6'h0;
      queue_inst_prj_2 <= 6'h0;
      queue_inst_prj_3 <= 6'h0;
      queue_inst_prk_0 <= 6'h0;
      queue_inst_prk_1 <= 6'h0;
      queue_inst_prk_2 <= 6'h0;
      queue_inst_prk_3 <= 6'h0;
      queue_inst_rd_valid_0 <= 1'h0;
      queue_inst_rd_valid_1 <= 1'h0;
      queue_inst_rd_valid_2 <= 1'h0;
      queue_inst_rd_valid_3 <= 1'h0;
      queue_inst_prd_0 <= 6'h0;
      queue_inst_prd_1 <= 6'h0;
      queue_inst_prd_2 <= 6'h0;
      queue_inst_prd_3 <= 6'h0;
      queue_inst_imm_0 <= 32'h0;
      queue_inst_imm_1 <= 32'h0;
      queue_inst_imm_2 <= 32'h0;
      queue_inst_imm_3 <= 32'h0;
      queue_inst_rob_index_0 <= 5'h0;
      queue_inst_rob_index_1 <= 5'h0;
      queue_inst_rob_index_2 <= 5'h0;
      queue_inst_rob_index_3 <= 5'h0;
      queue_inst_priv_vec_0 <= 10'h0;
      queue_inst_priv_vec_1 <= 10'h0;
      queue_inst_priv_vec_2 <= 10'h0;
      queue_inst_priv_vec_3 <= 10'h0;
      queue_inst_alu_op_0 <= 4'h0;
      queue_inst_alu_op_1 <= 4'h0;
      queue_inst_alu_op_2 <= 4'h0;
      queue_inst_alu_op_3 <= 4'h0;
      queue_prj_waked_0 <= 1'h0;
      queue_prj_waked_1 <= 1'h0;
      queue_prj_waked_2 <= 1'h0;
      queue_prj_waked_3 <= 1'h0;
      queue_prk_waked_0 <= 1'h0;
      queue_prk_waked_1 <= 1'h0;
      queue_prk_waked_2 <= 1'h0;
      queue_prk_waked_3 <= 1'h0;
      queue_prj_wake_by_ld_0 <= 1'h0;
      queue_prj_wake_by_ld_1 <= 1'h0;
      queue_prj_wake_by_ld_2 <= 1'h0;
      queue_prj_wake_by_ld_3 <= 1'h0;
      queue_prk_wake_by_ld_0 <= 1'h0;
      queue_prk_wake_by_ld_1 <= 1'h0;
      queue_prk_wake_by_ld_2 <= 1'h0;
      queue_prk_wake_by_ld_3 <= 1'h0;
      num <= 3'h0;
      qvalid <= 4'h0;
    end
    else begin
      if (qvalid[0]) begin
        if (io_issue_ack) begin
          queue_inst_prj_0 <= queue_inst_prj_1;
          queue_inst_prk_0 <= queue_inst_prk_1;
          queue_inst_rd_valid_0 <= queue_inst_rd_valid_1;
          queue_inst_prd_0 <= queue_inst_prd_1;
          queue_inst_imm_0 <= queue_inst_imm_1;
          queue_inst_rob_index_0 <= queue_inst_rob_index_1;
          queue_inst_priv_vec_0 <= queue_inst_priv_vec_1;
          queue_inst_alu_op_0 <= queue_inst_alu_op_1;
        end
      end
      else begin
        queue_inst_prj_0 <= _GEN_1;
        queue_inst_prk_0 <= _GEN_2;
        queue_inst_rd_valid_0 <=
          _GEN_0 ? io_insts_dispatch_rd_valid_1 : io_insts_dispatch_rd_valid_0;
        queue_inst_prd_0 <= _GEN_0 ? io_insts_dispatch_prd_1 : io_insts_dispatch_prd_0;
        queue_inst_imm_0 <= _GEN_0 ? io_insts_dispatch_imm_1 : io_insts_dispatch_imm_0;
        queue_inst_rob_index_0 <=
          _GEN_0 ? io_insts_dispatch_rob_index_1 : io_insts_dispatch_rob_index_0;
        queue_inst_priv_vec_0 <=
          _GEN_0 ? io_insts_dispatch_priv_vec_1 : io_insts_dispatch_priv_vec_0;
        queue_inst_alu_op_0 <=
          _GEN_0 ? io_insts_dispatch_alu_op_1 : io_insts_dispatch_alu_op_0;
      end
      if (qvalid[1]) begin
        if (io_issue_ack) begin
          queue_inst_prj_1 <= queue_inst_prj_2;
          queue_inst_prk_1 <= queue_inst_prk_2;
          queue_inst_rd_valid_1 <= queue_inst_rd_valid_2;
          queue_inst_prd_1 <= queue_inst_prd_2;
          queue_inst_imm_1 <= queue_inst_imm_2;
          queue_inst_rob_index_1 <= queue_inst_rob_index_2;
          queue_inst_priv_vec_1 <= queue_inst_priv_vec_2;
          queue_inst_alu_op_1 <= queue_inst_alu_op_2;
        end
      end
      else begin
        queue_inst_prj_1 <= _GEN_4;
        queue_inst_prk_1 <= _GEN_5;
        queue_inst_rd_valid_1 <=
          _GEN_3 ? io_insts_dispatch_rd_valid_1 : io_insts_dispatch_rd_valid_0;
        queue_inst_prd_1 <= _GEN_3 ? io_insts_dispatch_prd_1 : io_insts_dispatch_prd_0;
        queue_inst_imm_1 <= _GEN_3 ? io_insts_dispatch_imm_1 : io_insts_dispatch_imm_0;
        queue_inst_rob_index_1 <=
          _GEN_3 ? io_insts_dispatch_rob_index_1 : io_insts_dispatch_rob_index_0;
        queue_inst_priv_vec_1 <=
          _GEN_3 ? io_insts_dispatch_priv_vec_1 : io_insts_dispatch_priv_vec_0;
        queue_inst_alu_op_1 <=
          _GEN_3 ? io_insts_dispatch_alu_op_1 : io_insts_dispatch_alu_op_0;
      end
      if (qvalid[2]) begin
        if (io_issue_ack) begin
          queue_inst_prj_2 <= queue_inst_prj_3;
          queue_inst_prk_2 <= queue_inst_prk_3;
          queue_inst_rd_valid_2 <= queue_inst_rd_valid_3;
          queue_inst_prd_2 <= queue_inst_prd_3;
          queue_inst_imm_2 <= queue_inst_imm_3;
          queue_inst_rob_index_2 <= queue_inst_rob_index_3;
          queue_inst_priv_vec_2 <= queue_inst_priv_vec_3;
          queue_inst_alu_op_2 <= queue_inst_alu_op_3;
        end
      end
      else begin
        queue_inst_prj_2 <= _GEN_7;
        queue_inst_prk_2 <= _GEN_8;
        queue_inst_rd_valid_2 <=
          _GEN_6 ? io_insts_dispatch_rd_valid_1 : io_insts_dispatch_rd_valid_0;
        queue_inst_prd_2 <= _GEN_6 ? io_insts_dispatch_prd_1 : io_insts_dispatch_prd_0;
        queue_inst_imm_2 <= _GEN_6 ? io_insts_dispatch_imm_1 : io_insts_dispatch_imm_0;
        queue_inst_rob_index_2 <=
          _GEN_6 ? io_insts_dispatch_rob_index_1 : io_insts_dispatch_rob_index_0;
        queue_inst_priv_vec_2 <=
          _GEN_6 ? io_insts_dispatch_priv_vec_1 : io_insts_dispatch_priv_vec_0;
        queue_inst_alu_op_2 <=
          _GEN_6 ? io_insts_dispatch_alu_op_1 : io_insts_dispatch_alu_op_0;
      end
      if (qvalid[3]) begin
      end
      else begin
        queue_inst_prj_3 <= _GEN_10;
        queue_inst_prk_3 <= _GEN_11;
        queue_inst_rd_valid_3 <=
          _GEN_9 ? io_insts_dispatch_rd_valid_1 : io_insts_dispatch_rd_valid_0;
        queue_inst_prd_3 <= _GEN_9 ? io_insts_dispatch_prd_1 : io_insts_dispatch_prd_0;
        queue_inst_imm_3 <= _GEN_9 ? io_insts_dispatch_imm_1 : io_insts_dispatch_imm_0;
        queue_inst_rob_index_3 <=
          _GEN_9 ? io_insts_dispatch_rob_index_1 : io_insts_dispatch_rob_index_0;
        queue_inst_priv_vec_3 <=
          _GEN_9 ? io_insts_dispatch_priv_vec_1 : io_insts_dispatch_priv_vec_0;
        queue_inst_alu_op_3 <=
          _GEN_9 ? io_insts_dispatch_alu_op_1 : io_insts_dispatch_alu_op_0;
      end
      queue_prj_waked_0 <=
        queue_next_prj_waked
        | (|{~(|_queue_0_prj_wake_by_ld_T),
             (queue_next_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_prj_waked_1 <=
        queue_next_1_prj_waked
        | (|{~(|_queue_1_prj_wake_by_ld_T),
             (queue_next_1_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_prj_waked_2 <=
        queue_next_2_prj_waked
        | (|{~(|_queue_2_prj_wake_by_ld_T),
             (queue_next_2_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_prj_waked_3 <=
        queue_next_3_prj_waked
        | (|{~(|_queue_3_prj_wake_by_ld_T),
             (queue_next_3_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_prk_waked_0 <=
        queue_next_prk_waked
        | (|{~(|_queue_0_prk_wake_by_ld_T),
             (queue_next_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_prk_waked_1 <=
        queue_next_1_prk_waked
        | (|{~(|_queue_1_prk_wake_by_ld_T),
             (queue_next_1_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_prk_waked_2 <=
        queue_next_2_prk_waked
        | (|{~(|_queue_2_prk_wake_by_ld_T),
             (queue_next_2_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_prk_waked_3 <=
        queue_next_3_prk_waked
        | (|{~(|_queue_3_prk_wake_by_ld_T),
             (queue_next_3_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_prj_wake_by_ld_0 <=
        ~(|_queue_0_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_prj_wake_by_ld;
      queue_prj_wake_by_ld_1 <=
        ~(|_queue_1_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_1_prj_wake_by_ld;
      queue_prj_wake_by_ld_2 <=
        ~(|_queue_2_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_2_prj_wake_by_ld;
      queue_prj_wake_by_ld_3 <=
        ~(|_queue_3_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_3_prj_wake_by_ld;
      queue_prk_wake_by_ld_0 <=
        ~(|_queue_0_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_prk_wake_by_ld;
      queue_prk_wake_by_ld_1 <=
        ~(|_queue_1_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_1_prk_wake_by_ld;
      queue_prk_wake_by_ld_2 <=
        ~(|_queue_2_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_2_prk_wake_by_ld;
      queue_prk_wake_by_ld_3 <=
        ~(|_queue_3_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_3_prk_wake_by_ld;
      if (io_flush) begin
        num <= 3'h0;
        qvalid <= 4'h0;
      end
      else begin
        if (io_stall | qvalid[2])
          num <= _num_pop_T_1;
        else
          num <= 3'(_num_pop_T_1 + {1'h0, ins_num});
        if (io_stall) begin
        end
        else if (ins_num == 2'h2)
          qvalid <= {qvalid[1:0], 2'h3};
        else if (ins_num == 2'h1)
          qvalid <= {qvalid[2:0], 1'h1};
      end
    end
  end // always @(posedge)
  assign io_insts_issue_inst_prj = queue_inst_prj_0;
  assign io_insts_issue_inst_prk = queue_inst_prk_0;
  assign io_insts_issue_inst_rd_valid = queue_inst_rd_valid_0;
  assign io_insts_issue_inst_prd = queue_inst_prd_0;
  assign io_insts_issue_inst_imm = queue_inst_imm_0;
  assign io_insts_issue_inst_rob_index = queue_inst_rob_index_0;
  assign io_insts_issue_inst_priv_vec = queue_inst_priv_vec_0;
  assign io_insts_issue_inst_alu_op = queue_inst_alu_op_0;
  assign io_issue_req =
    qvalid[0] & queue_prj_waked_0 & queue_prk_waked_0
    & ~((queue_prj_wake_by_ld_0 & (queue_inst_prj_0 ^ io_ld_mem_prd) == 6'h0
         | queue_prk_wake_by_ld_0 & (queue_inst_prk_0 ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_full = qvalid[2];
endmodule

