// Generated by CIRCT firtool-1.62.0
module Unorder_Select_1(
  input  [5:0]  io_insts_issue_0_inst_prj,
                io_insts_issue_0_inst_prk,
  input         io_insts_issue_0_inst_rd_valid,
  input  [5:0]  io_insts_issue_0_inst_prd,
  input  [31:0] io_insts_issue_0_inst_imm,
  input  [4:0]  io_insts_issue_0_inst_rob_index,
  input  [3:0]  io_insts_issue_0_inst_alu_op,
  input         io_insts_issue_0_inst_alu_rs1_sel,
  input  [1:0]  io_insts_issue_0_inst_alu_rs2_sel,
  input  [31:0] io_insts_issue_0_inst_pc,
  input  [3:0]  io_insts_issue_0_inst_br_type,
  input         io_insts_issue_0_inst_predict_jump,
  input  [31:0] io_insts_issue_0_inst_pred_npc,
  input  [5:0]  io_insts_issue_1_inst_prj,
                io_insts_issue_1_inst_prk,
  input         io_insts_issue_1_inst_rd_valid,
  input  [5:0]  io_insts_issue_1_inst_prd,
  input  [31:0] io_insts_issue_1_inst_imm,
  input  [4:0]  io_insts_issue_1_inst_rob_index,
  input  [3:0]  io_insts_issue_1_inst_alu_op,
  input         io_insts_issue_1_inst_alu_rs1_sel,
  input  [1:0]  io_insts_issue_1_inst_alu_rs2_sel,
  input  [31:0] io_insts_issue_1_inst_pc,
  input  [3:0]  io_insts_issue_1_inst_br_type,
  input         io_insts_issue_1_inst_predict_jump,
  input  [31:0] io_insts_issue_1_inst_pred_npc,
  input  [5:0]  io_insts_issue_2_inst_prj,
                io_insts_issue_2_inst_prk,
  input         io_insts_issue_2_inst_rd_valid,
  input  [5:0]  io_insts_issue_2_inst_prd,
  input  [31:0] io_insts_issue_2_inst_imm,
  input  [4:0]  io_insts_issue_2_inst_rob_index,
  input  [3:0]  io_insts_issue_2_inst_alu_op,
  input         io_insts_issue_2_inst_alu_rs1_sel,
  input  [1:0]  io_insts_issue_2_inst_alu_rs2_sel,
  input  [31:0] io_insts_issue_2_inst_pc,
  input  [3:0]  io_insts_issue_2_inst_br_type,
  input         io_insts_issue_2_inst_predict_jump,
  input  [31:0] io_insts_issue_2_inst_pred_npc,
  input  [5:0]  io_insts_issue_3_inst_prj,
                io_insts_issue_3_inst_prk,
  input         io_insts_issue_3_inst_rd_valid,
  input  [5:0]  io_insts_issue_3_inst_prd,
  input  [31:0] io_insts_issue_3_inst_imm,
  input  [4:0]  io_insts_issue_3_inst_rob_index,
  input  [3:0]  io_insts_issue_3_inst_alu_op,
  input         io_insts_issue_3_inst_alu_rs1_sel,
  input  [1:0]  io_insts_issue_3_inst_alu_rs2_sel,
  input  [31:0] io_insts_issue_3_inst_pc,
  input  [3:0]  io_insts_issue_3_inst_br_type,
  input         io_insts_issue_3_inst_predict_jump,
  input  [31:0] io_insts_issue_3_inst_pred_npc,
  input  [5:0]  io_insts_issue_4_inst_prj,
                io_insts_issue_4_inst_prk,
  input         io_insts_issue_4_inst_rd_valid,
  input  [5:0]  io_insts_issue_4_inst_prd,
  input  [31:0] io_insts_issue_4_inst_imm,
  input  [4:0]  io_insts_issue_4_inst_rob_index,
  input  [3:0]  io_insts_issue_4_inst_alu_op,
  input         io_insts_issue_4_inst_alu_rs1_sel,
  input  [1:0]  io_insts_issue_4_inst_alu_rs2_sel,
  input  [31:0] io_insts_issue_4_inst_pc,
  input  [3:0]  io_insts_issue_4_inst_br_type,
  input         io_insts_issue_4_inst_predict_jump,
  input  [31:0] io_insts_issue_4_inst_pred_npc,
  input  [5:0]  io_insts_issue_5_inst_prj,
                io_insts_issue_5_inst_prk,
  input         io_insts_issue_5_inst_rd_valid,
  input  [5:0]  io_insts_issue_5_inst_prd,
  input  [31:0] io_insts_issue_5_inst_imm,
  input  [4:0]  io_insts_issue_5_inst_rob_index,
  input  [3:0]  io_insts_issue_5_inst_alu_op,
  input         io_insts_issue_5_inst_alu_rs1_sel,
  input  [1:0]  io_insts_issue_5_inst_alu_rs2_sel,
  input  [31:0] io_insts_issue_5_inst_pc,
  input  [3:0]  io_insts_issue_5_inst_br_type,
  input         io_insts_issue_5_inst_predict_jump,
  input  [31:0] io_insts_issue_5_inst_pred_npc,
  input         io_issue_req_0,
                io_issue_req_1,
                io_issue_req_2,
                io_issue_req_3,
                io_issue_req_4,
                io_issue_req_5,
                io_stall,
  output        io_issue_ack_0,
                io_issue_ack_1,
                io_issue_ack_2,
                io_issue_ack_3,
                io_issue_ack_4,
                io_issue_ack_5,
  output [5:0]  io_wake_preg,
                io_inst_issue_inst_prj,
                io_inst_issue_inst_prk,
  output        io_inst_issue_inst_rd_valid,
  output [5:0]  io_inst_issue_inst_prd,
  output [31:0] io_inst_issue_inst_imm,
  output [4:0]  io_inst_issue_inst_rob_index,
  output [3:0]  io_inst_issue_inst_alu_op,
  output        io_inst_issue_inst_alu_rs1_sel,
  output [1:0]  io_inst_issue_inst_alu_rs2_sel,
  output [31:0] io_inst_issue_inst_pc,
  output [3:0]  io_inst_issue_inst_br_type,
  output        io_inst_issue_inst_predict_jump,
  output [31:0] io_inst_issue_inst_pred_npc,
  output        io_inst_issue_valid
);

  wire [5:0]  _select_enc_T_1 = io_issue_req_4 ? 6'h10 : {io_issue_req_5, 5'h0};
  wire [5:0]  _select_enc_T_2 = io_issue_req_3 ? 6'h8 : _select_enc_T_1;
  wire [5:0]  _select_enc_T_3 = io_issue_req_2 ? 6'h4 : _select_enc_T_2;
  wire [5:0]  _select_enc_T_4 = io_issue_req_1 ? 6'h2 : _select_enc_T_3;
  wire [5:0]  select_enc = io_issue_req_0 ? 6'h1 : _select_enc_T_4;
  wire [31:0] _inst_T_44 = select_enc[0] ? io_insts_issue_0_inst_pred_npc : 32'h0;
  wire [31:0] _inst_T_45 = select_enc[1] ? io_insts_issue_1_inst_pred_npc : 32'h0;
  wire [31:0] _inst_T_46 = select_enc[2] ? io_insts_issue_2_inst_pred_npc : 32'h0;
  wire [31:0] _inst_T_47 = select_enc[3] ? io_insts_issue_3_inst_pred_npc : 32'h0;
  wire [31:0] _inst_T_48 = select_enc[4] ? io_insts_issue_4_inst_pred_npc : 32'h0;
  wire [31:0] _inst_T_49 = select_enc[5] ? io_insts_issue_5_inst_pred_npc : 32'h0;
  wire [3:0]  _inst_T_66 = select_enc[0] ? io_insts_issue_0_inst_br_type : 4'h0;
  wire [3:0]  _inst_T_67 = select_enc[1] ? io_insts_issue_1_inst_br_type : 4'h0;
  wire [3:0]  _inst_T_68 = select_enc[2] ? io_insts_issue_2_inst_br_type : 4'h0;
  wire [3:0]  _inst_T_69 = select_enc[3] ? io_insts_issue_3_inst_br_type : 4'h0;
  wire [3:0]  _inst_T_70 = select_enc[4] ? io_insts_issue_4_inst_br_type : 4'h0;
  wire [3:0]  _inst_T_71 = select_enc[5] ? io_insts_issue_5_inst_br_type : 4'h0;
  wire [31:0] _inst_T_77 = select_enc[0] ? io_insts_issue_0_inst_pc : 32'h0;
  wire [31:0] _inst_T_78 = select_enc[1] ? io_insts_issue_1_inst_pc : 32'h0;
  wire [31:0] _inst_T_79 = select_enc[2] ? io_insts_issue_2_inst_pc : 32'h0;
  wire [31:0] _inst_T_80 = select_enc[3] ? io_insts_issue_3_inst_pc : 32'h0;
  wire [31:0] _inst_T_81 = select_enc[4] ? io_insts_issue_4_inst_pc : 32'h0;
  wire [31:0] _inst_T_82 = select_enc[5] ? io_insts_issue_5_inst_pc : 32'h0;
  wire [1:0]  _inst_T_88 = select_enc[0] ? io_insts_issue_0_inst_alu_rs2_sel : 2'h0;
  wire [1:0]  _inst_T_89 = select_enc[1] ? io_insts_issue_1_inst_alu_rs2_sel : 2'h0;
  wire [1:0]  _inst_T_90 = select_enc[2] ? io_insts_issue_2_inst_alu_rs2_sel : 2'h0;
  wire [1:0]  _inst_T_91 = select_enc[3] ? io_insts_issue_3_inst_alu_rs2_sel : 2'h0;
  wire [1:0]  _inst_T_92 = select_enc[4] ? io_insts_issue_4_inst_alu_rs2_sel : 2'h0;
  wire [1:0]  _inst_T_93 = select_enc[5] ? io_insts_issue_5_inst_alu_rs2_sel : 2'h0;
  wire [3:0]  _inst_T_110 = select_enc[0] ? io_insts_issue_0_inst_alu_op : 4'h0;
  wire [3:0]  _inst_T_111 = select_enc[1] ? io_insts_issue_1_inst_alu_op : 4'h0;
  wire [3:0]  _inst_T_112 = select_enc[2] ? io_insts_issue_2_inst_alu_op : 4'h0;
  wire [3:0]  _inst_T_113 = select_enc[3] ? io_insts_issue_3_inst_alu_op : 4'h0;
  wire [3:0]  _inst_T_114 = select_enc[4] ? io_insts_issue_4_inst_alu_op : 4'h0;
  wire [3:0]  _inst_T_115 = select_enc[5] ? io_insts_issue_5_inst_alu_op : 4'h0;
  wire [4:0]  _inst_T_121 = select_enc[0] ? io_insts_issue_0_inst_rob_index : 5'h0;
  wire [4:0]  _inst_T_122 = select_enc[1] ? io_insts_issue_1_inst_rob_index : 5'h0;
  wire [4:0]  _inst_T_123 = select_enc[2] ? io_insts_issue_2_inst_rob_index : 5'h0;
  wire [4:0]  _inst_T_124 = select_enc[3] ? io_insts_issue_3_inst_rob_index : 5'h0;
  wire [4:0]  _inst_T_125 = select_enc[4] ? io_insts_issue_4_inst_rob_index : 5'h0;
  wire [4:0]  _inst_T_126 = select_enc[5] ? io_insts_issue_5_inst_rob_index : 5'h0;
  wire [31:0] _inst_T_132 = select_enc[0] ? io_insts_issue_0_inst_imm : 32'h0;
  wire [31:0] _inst_T_133 = select_enc[1] ? io_insts_issue_1_inst_imm : 32'h0;
  wire [31:0] _inst_T_134 = select_enc[2] ? io_insts_issue_2_inst_imm : 32'h0;
  wire [31:0] _inst_T_135 = select_enc[3] ? io_insts_issue_3_inst_imm : 32'h0;
  wire [31:0] _inst_T_136 = select_enc[4] ? io_insts_issue_4_inst_imm : 32'h0;
  wire [31:0] _inst_T_137 = select_enc[5] ? io_insts_issue_5_inst_imm : 32'h0;
  wire [5:0]  _io_wake_preg_T = select_enc[0] ? io_insts_issue_0_inst_prd : 6'h0;
  wire [5:0]  _io_wake_preg_T_1 = select_enc[1] ? io_insts_issue_1_inst_prd : 6'h0;
  wire [5:0]  _io_wake_preg_T_2 = select_enc[2] ? io_insts_issue_2_inst_prd : 6'h0;
  wire [5:0]  _io_wake_preg_T_3 = select_enc[3] ? io_insts_issue_3_inst_prd : 6'h0;
  wire [5:0]  _io_wake_preg_T_4 = select_enc[4] ? io_insts_issue_4_inst_prd : 6'h0;
  wire [5:0]  _io_wake_preg_T_5 = select_enc[5] ? io_insts_issue_5_inst_prd : 6'h0;
  wire [5:0]  _inst_T_165 = select_enc[0] ? io_insts_issue_0_inst_prk : 6'h0;
  wire [5:0]  _inst_T_166 = select_enc[1] ? io_insts_issue_1_inst_prk : 6'h0;
  wire [5:0]  _inst_T_167 = select_enc[2] ? io_insts_issue_2_inst_prk : 6'h0;
  wire [5:0]  _inst_T_168 = select_enc[3] ? io_insts_issue_3_inst_prk : 6'h0;
  wire [5:0]  _inst_T_169 = select_enc[4] ? io_insts_issue_4_inst_prk : 6'h0;
  wire [5:0]  _inst_T_170 = select_enc[5] ? io_insts_issue_5_inst_prk : 6'h0;
  wire [5:0]  _inst_T_176 = select_enc[0] ? io_insts_issue_0_inst_prj : 6'h0;
  wire [5:0]  _inst_T_177 = select_enc[1] ? io_insts_issue_1_inst_prj : 6'h0;
  wire [5:0]  _inst_T_178 = select_enc[2] ? io_insts_issue_2_inst_prj : 6'h0;
  wire [5:0]  _inst_T_179 = select_enc[3] ? io_insts_issue_3_inst_prj : 6'h0;
  wire [5:0]  _inst_T_180 = select_enc[4] ? io_insts_issue_4_inst_prj : 6'h0;
  wire [5:0]  _inst_T_181 = select_enc[5] ? io_insts_issue_5_inst_prj : 6'h0;
  wire        choice =
    (|{io_issue_req_5,
       io_issue_req_4,
       io_issue_req_3,
       io_issue_req_2,
       io_issue_req_1,
       io_issue_req_0}) & ~io_stall;
  assign io_issue_ack_0 = choice & select_enc[0];
  assign io_issue_ack_1 = choice & select_enc[1];
  assign io_issue_ack_2 = choice & select_enc[2];
  assign io_issue_ack_3 = choice & select_enc[3];
  assign io_issue_ack_4 = choice & select_enc[4];
  assign io_issue_ack_5 = choice & select_enc[5];
  assign io_wake_preg =
    choice
      ? _io_wake_preg_T | _io_wake_preg_T_1 | _io_wake_preg_T_2 | _io_wake_preg_T_3
        | _io_wake_preg_T_4 | _io_wake_preg_T_5
      : 6'h0;
  assign io_inst_issue_inst_prj =
    choice
      ? _inst_T_176 | _inst_T_177 | _inst_T_178 | _inst_T_179 | _inst_T_180 | _inst_T_181
      : 6'h0;
  assign io_inst_issue_inst_prk =
    choice
      ? _inst_T_165 | _inst_T_166 | _inst_T_167 | _inst_T_168 | _inst_T_169 | _inst_T_170
      : 6'h0;
  assign io_inst_issue_inst_rd_valid =
    choice
    & (select_enc[0] & io_insts_issue_0_inst_rd_valid | select_enc[1]
       & io_insts_issue_1_inst_rd_valid | select_enc[2] & io_insts_issue_2_inst_rd_valid
       | select_enc[3] & io_insts_issue_3_inst_rd_valid | select_enc[4]
       & io_insts_issue_4_inst_rd_valid | select_enc[5] & io_insts_issue_5_inst_rd_valid);
  assign io_inst_issue_inst_prd =
    choice
      ? _io_wake_preg_T | _io_wake_preg_T_1 | _io_wake_preg_T_2 | _io_wake_preg_T_3
        | _io_wake_preg_T_4 | _io_wake_preg_T_5
      : 6'h0;
  assign io_inst_issue_inst_imm =
    choice
      ? _inst_T_132 | _inst_T_133 | _inst_T_134 | _inst_T_135 | _inst_T_136 | _inst_T_137
      : 32'h0;
  assign io_inst_issue_inst_rob_index =
    choice
      ? _inst_T_121 | _inst_T_122 | _inst_T_123 | _inst_T_124 | _inst_T_125 | _inst_T_126
      : 5'h0;
  assign io_inst_issue_inst_alu_op =
    choice
      ? _inst_T_110 | _inst_T_111 | _inst_T_112 | _inst_T_113 | _inst_T_114 | _inst_T_115
      : 4'h0;
  assign io_inst_issue_inst_alu_rs1_sel =
    choice
    & (select_enc[0] & io_insts_issue_0_inst_alu_rs1_sel | select_enc[1]
       & io_insts_issue_1_inst_alu_rs1_sel | select_enc[2]
       & io_insts_issue_2_inst_alu_rs1_sel | select_enc[3]
       & io_insts_issue_3_inst_alu_rs1_sel | select_enc[4]
       & io_insts_issue_4_inst_alu_rs1_sel | select_enc[5]
       & io_insts_issue_5_inst_alu_rs1_sel);
  assign io_inst_issue_inst_alu_rs2_sel =
    choice
      ? _inst_T_88 | _inst_T_89 | _inst_T_90 | _inst_T_91 | _inst_T_92 | _inst_T_93
      : 2'h0;
  assign io_inst_issue_inst_pc =
    choice
      ? _inst_T_77 | _inst_T_78 | _inst_T_79 | _inst_T_80 | _inst_T_81 | _inst_T_82
      : 32'h0;
  assign io_inst_issue_inst_br_type =
    choice
      ? _inst_T_66 | _inst_T_67 | _inst_T_68 | _inst_T_69 | _inst_T_70 | _inst_T_71
      : 4'h0;
  assign io_inst_issue_inst_predict_jump =
    choice
    & (select_enc[0] & io_insts_issue_0_inst_predict_jump | select_enc[1]
       & io_insts_issue_1_inst_predict_jump | select_enc[2]
       & io_insts_issue_2_inst_predict_jump | select_enc[3]
       & io_insts_issue_3_inst_predict_jump | select_enc[4]
       & io_insts_issue_4_inst_predict_jump | select_enc[5]
       & io_insts_issue_5_inst_predict_jump);
  assign io_inst_issue_inst_pred_npc =
    choice
      ? _inst_T_44 | _inst_T_45 | _inst_T_46 | _inst_T_47 | _inst_T_48 | _inst_T_49
      : 32'h0;
  assign io_inst_issue_valid = choice;
endmodule

