// Generated by CIRCT firtool-1.62.0
module Unorder_Issue_Queue(
  input         clock,
                reset,
                io_insts_disp_valid_0,
                io_insts_disp_valid_1,
  input  [5:0]  io_insts_dispatch_0_prj,
                io_insts_dispatch_0_prk,
  input         io_insts_dispatch_0_rd_valid,
  input  [5:0]  io_insts_dispatch_0_prd,
  input  [31:0] io_insts_dispatch_0_imm,
  input  [4:0]  io_insts_dispatch_0_rob_index,
  input  [3:0]  io_insts_dispatch_0_alu_op,
  input         io_insts_dispatch_0_alu_rs1_sel,
  input  [1:0]  io_insts_dispatch_0_alu_rs2_sel,
  input  [31:0] io_insts_dispatch_0_pc,
  input  [5:0]  io_insts_dispatch_1_prj,
                io_insts_dispatch_1_prk,
  input         io_insts_dispatch_1_rd_valid,
  input  [5:0]  io_insts_dispatch_1_prd,
  input  [31:0] io_insts_dispatch_1_imm,
  input  [4:0]  io_insts_dispatch_1_rob_index,
  input  [3:0]  io_insts_dispatch_1_alu_op,
  input         io_insts_dispatch_1_alu_rs1_sel,
  input  [1:0]  io_insts_dispatch_1_alu_rs2_sel,
  input  [31:0] io_insts_dispatch_1_pc,
  input         io_prj_ready_0,
                io_prj_ready_1,
                io_prk_ready_0,
                io_prk_ready_1,
  input  [5:0]  io_wake_preg_0,
                io_wake_preg_1,
                io_wake_preg_2,
                io_wake_preg_3,
  input         io_issue_ack_0,
                io_issue_ack_1,
                io_issue_ack_2,
                io_issue_ack_3,
                io_issue_ack_4,
                io_issue_ack_5,
  output [5:0]  io_insts_issue_0_inst_prj,
                io_insts_issue_0_inst_prk,
  output        io_insts_issue_0_inst_rd_valid,
  output [5:0]  io_insts_issue_0_inst_prd,
  output [31:0] io_insts_issue_0_inst_imm,
  output [4:0]  io_insts_issue_0_inst_rob_index,
  output [3:0]  io_insts_issue_0_inst_alu_op,
  output        io_insts_issue_0_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_0_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_0_inst_pc,
  output [5:0]  io_insts_issue_1_inst_prj,
                io_insts_issue_1_inst_prk,
  output        io_insts_issue_1_inst_rd_valid,
  output [5:0]  io_insts_issue_1_inst_prd,
  output [31:0] io_insts_issue_1_inst_imm,
  output [4:0]  io_insts_issue_1_inst_rob_index,
  output [3:0]  io_insts_issue_1_inst_alu_op,
  output        io_insts_issue_1_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_1_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_1_inst_pc,
  output [5:0]  io_insts_issue_2_inst_prj,
                io_insts_issue_2_inst_prk,
  output        io_insts_issue_2_inst_rd_valid,
  output [5:0]  io_insts_issue_2_inst_prd,
  output [31:0] io_insts_issue_2_inst_imm,
  output [4:0]  io_insts_issue_2_inst_rob_index,
  output [3:0]  io_insts_issue_2_inst_alu_op,
  output        io_insts_issue_2_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_2_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_2_inst_pc,
  output [5:0]  io_insts_issue_3_inst_prj,
                io_insts_issue_3_inst_prk,
  output        io_insts_issue_3_inst_rd_valid,
  output [5:0]  io_insts_issue_3_inst_prd,
  output [31:0] io_insts_issue_3_inst_imm,
  output [4:0]  io_insts_issue_3_inst_rob_index,
  output [3:0]  io_insts_issue_3_inst_alu_op,
  output        io_insts_issue_3_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_3_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_3_inst_pc,
  output [5:0]  io_insts_issue_4_inst_prj,
                io_insts_issue_4_inst_prk,
  output        io_insts_issue_4_inst_rd_valid,
  output [5:0]  io_insts_issue_4_inst_prd,
  output [31:0] io_insts_issue_4_inst_imm,
  output [4:0]  io_insts_issue_4_inst_rob_index,
  output [3:0]  io_insts_issue_4_inst_alu_op,
  output        io_insts_issue_4_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_4_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_4_inst_pc,
  output [5:0]  io_insts_issue_5_inst_prj,
                io_insts_issue_5_inst_prk,
  output        io_insts_issue_5_inst_rd_valid,
  output [5:0]  io_insts_issue_5_inst_prd,
  output [31:0] io_insts_issue_5_inst_imm,
  output [4:0]  io_insts_issue_5_inst_rob_index,
  output [3:0]  io_insts_issue_5_inst_alu_op,
  output        io_insts_issue_5_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_5_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_5_inst_pc,
  output        io_issue_req_0,
                io_issue_req_1,
                io_issue_req_2,
                io_issue_req_3,
                io_issue_req_4,
                io_issue_req_5,
  output [3:0]  io_elem_num,
  output        io_full,
  input         io_stall,
                io_flush
);

  reg  [5:0]  queue_0_inst_prj;
  reg  [5:0]  queue_0_inst_prk;
  reg         queue_0_inst_rd_valid;
  reg  [5:0]  queue_0_inst_prd;
  reg  [31:0] queue_0_inst_imm;
  reg  [4:0]  queue_0_inst_rob_index;
  reg  [3:0]  queue_0_inst_alu_op;
  reg         queue_0_inst_alu_rs1_sel;
  reg  [1:0]  queue_0_inst_alu_rs2_sel;
  reg  [31:0] queue_0_inst_pc;
  reg         queue_0_prj_waked;
  reg         queue_0_prk_waked;
  reg  [5:0]  queue_1_inst_prj;
  reg  [5:0]  queue_1_inst_prk;
  reg         queue_1_inst_rd_valid;
  reg  [5:0]  queue_1_inst_prd;
  reg  [31:0] queue_1_inst_imm;
  reg  [4:0]  queue_1_inst_rob_index;
  reg  [3:0]  queue_1_inst_alu_op;
  reg         queue_1_inst_alu_rs1_sel;
  reg  [1:0]  queue_1_inst_alu_rs2_sel;
  reg  [31:0] queue_1_inst_pc;
  reg         queue_1_prj_waked;
  reg         queue_1_prk_waked;
  reg  [5:0]  queue_2_inst_prj;
  reg  [5:0]  queue_2_inst_prk;
  reg         queue_2_inst_rd_valid;
  reg  [5:0]  queue_2_inst_prd;
  reg  [31:0] queue_2_inst_imm;
  reg  [4:0]  queue_2_inst_rob_index;
  reg  [3:0]  queue_2_inst_alu_op;
  reg         queue_2_inst_alu_rs1_sel;
  reg  [1:0]  queue_2_inst_alu_rs2_sel;
  reg  [31:0] queue_2_inst_pc;
  reg         queue_2_prj_waked;
  reg         queue_2_prk_waked;
  reg  [5:0]  queue_3_inst_prj;
  reg  [5:0]  queue_3_inst_prk;
  reg         queue_3_inst_rd_valid;
  reg  [5:0]  queue_3_inst_prd;
  reg  [31:0] queue_3_inst_imm;
  reg  [4:0]  queue_3_inst_rob_index;
  reg  [3:0]  queue_3_inst_alu_op;
  reg         queue_3_inst_alu_rs1_sel;
  reg  [1:0]  queue_3_inst_alu_rs2_sel;
  reg  [31:0] queue_3_inst_pc;
  reg         queue_3_prj_waked;
  reg         queue_3_prk_waked;
  reg  [5:0]  queue_4_inst_prj;
  reg  [5:0]  queue_4_inst_prk;
  reg         queue_4_inst_rd_valid;
  reg  [5:0]  queue_4_inst_prd;
  reg  [31:0] queue_4_inst_imm;
  reg  [4:0]  queue_4_inst_rob_index;
  reg  [3:0]  queue_4_inst_alu_op;
  reg         queue_4_inst_alu_rs1_sel;
  reg  [1:0]  queue_4_inst_alu_rs2_sel;
  reg  [31:0] queue_4_inst_pc;
  reg         queue_4_prj_waked;
  reg         queue_4_prk_waked;
  reg  [5:0]  queue_5_inst_prj;
  reg  [5:0]  queue_5_inst_prk;
  reg         queue_5_inst_rd_valid;
  reg  [5:0]  queue_5_inst_prd;
  reg  [31:0] queue_5_inst_imm;
  reg  [4:0]  queue_5_inst_rob_index;
  reg  [3:0]  queue_5_inst_alu_op;
  reg         queue_5_inst_alu_rs1_sel;
  reg  [1:0]  queue_5_inst_alu_rs2_sel;
  reg  [31:0] queue_5_inst_pc;
  reg         queue_5_prj_waked;
  reg         queue_5_prk_waked;
  reg  [3:0]  num;
  reg  [5:0]  qvalid;
  wire [1:0]  ins_num = 2'({1'h0, io_insts_disp_valid_0} + {1'h0, io_insts_disp_valid_1});
  wire [3:0]  _num_pop_T_2 =
    4'(num
       - {3'h0,
          |{io_issue_ack_5,
            io_issue_ack_4,
            io_issue_ack_3,
            io_issue_ack_2,
            io_issue_ack_1,
            io_issue_ack_0}});
  wire [5:0]  _qvalid_pop_T =
    {io_issue_ack_5,
     io_issue_ack_4,
     io_issue_ack_3,
     io_issue_ack_2,
     io_issue_ack_1,
     io_issue_ack_0};
  wire [5:0]  _qvalid_pop_T_3 = {1'h0, qvalid[5:1]};
  wire [5:0]  qvalid_pop = (|_qvalid_pop_T) ? _qvalid_pop_T_3 : qvalid;
  wire [4:0]  _issue_T_2 =
    5'(~{io_issue_ack_4, io_issue_ack_3, io_issue_ack_2, io_issue_ack_1, io_issue_ack_0}
       + 5'h1);
  wire        _GEN = io_insts_disp_valid_0 & ~io_insts_disp_valid_1;
  wire        _GEN_0 = _GEN | 1'(1'h0 - _num_pop_T_2[0]);
  wire [5:0]  _GEN_1 = _GEN_0 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_1_inst_prj =
    _issue_T_2[0] ? queue_1_inst_prj : queue_0_inst_prj;
  wire [5:0]  queue_next_inst_prj = qvalid_pop[0] ? _queue_next_T_1_inst_prj : _GEN_1;
  wire [5:0]  _GEN_2 = _GEN_0 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_1_inst_prk =
    _issue_T_2[0] ? queue_1_inst_prk : queue_0_inst_prk;
  wire [5:0]  queue_next_inst_prk = qvalid_pop[0] ? _queue_next_T_1_inst_prk : _GEN_2;
  wire        _GEN_3 = _GEN | 1'(1'h1 - _num_pop_T_2[0]);
  wire [5:0]  _GEN_4 = _GEN_3 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_3_inst_prj =
    _issue_T_2[1] ? queue_2_inst_prj : queue_1_inst_prj;
  wire [5:0]  queue_next_1_inst_prj = qvalid_pop[1] ? _queue_next_T_3_inst_prj : _GEN_4;
  wire [5:0]  _GEN_5 = _GEN_3 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_3_inst_prk =
    _issue_T_2[1] ? queue_2_inst_prk : queue_1_inst_prk;
  wire [5:0]  queue_next_1_inst_prk = qvalid_pop[1] ? _queue_next_T_3_inst_prk : _GEN_5;
  wire        _GEN_6 = _GEN | 1'(1'h0 - _num_pop_T_2[0]);
  wire [5:0]  _GEN_7 = _GEN_6 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_5_inst_prj =
    _issue_T_2[2] ? queue_3_inst_prj : queue_2_inst_prj;
  wire [5:0]  queue_next_2_inst_prj = qvalid_pop[2] ? _queue_next_T_5_inst_prj : _GEN_7;
  wire [5:0]  _GEN_8 = _GEN_6 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_5_inst_prk =
    _issue_T_2[2] ? queue_3_inst_prk : queue_2_inst_prk;
  wire [5:0]  queue_next_2_inst_prk = qvalid_pop[2] ? _queue_next_T_5_inst_prk : _GEN_8;
  wire        _GEN_9 = _GEN | 1'(1'h1 - _num_pop_T_2[0]);
  wire [5:0]  _GEN_10 = _GEN_9 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_7_inst_prj =
    _issue_T_2[3] ? queue_4_inst_prj : queue_3_inst_prj;
  wire [5:0]  queue_next_3_inst_prj = qvalid_pop[3] ? _queue_next_T_7_inst_prj : _GEN_10;
  wire [5:0]  _GEN_11 = _GEN_9 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_7_inst_prk =
    _issue_T_2[3] ? queue_4_inst_prk : queue_3_inst_prk;
  wire [5:0]  queue_next_3_inst_prk = qvalid_pop[3] ? _queue_next_T_7_inst_prk : _GEN_11;
  wire        _GEN_12 = _GEN | 1'(1'h0 - _num_pop_T_2[0]);
  wire [5:0]  _GEN_13 = _GEN_12 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _queue_next_T_9_inst_prj =
    _issue_T_2[4] ? queue_5_inst_prj : queue_4_inst_prj;
  wire [5:0]  queue_next_4_inst_prj = qvalid_pop[4] ? _queue_next_T_9_inst_prj : _GEN_13;
  wire [5:0]  _GEN_14 = _GEN_12 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_9_inst_prk =
    _issue_T_2[4] ? queue_5_inst_prk : queue_4_inst_prk;
  wire [5:0]  queue_next_4_inst_prk = qvalid_pop[4] ? _queue_next_T_9_inst_prk : _GEN_14;
  wire        _GEN_15 = _GEN | 1'(1'h1 - _num_pop_T_2[0]);
  wire [5:0]  _GEN_16 = _GEN_15 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  queue_next_5_inst_prj = qvalid_pop[5] ? queue_5_inst_prj : _GEN_16;
  wire [5:0]  _GEN_17 = _GEN_15 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  queue_next_5_inst_prk = qvalid_pop[5] ? queue_5_inst_prk : _GEN_17;
  wire        _GEN_18 = _GEN_0 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_1_prj_waked =
    _issue_T_2[0] ? queue_1_prj_waked : queue_0_prj_waked;
  wire        queue_next_prj_waked = qvalid_pop[0] ? _queue_next_T_1_prj_waked : _GEN_18;
  wire        _GEN_19 = _GEN_0 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_1_prk_waked =
    _issue_T_2[0] ? queue_1_prk_waked : queue_0_prk_waked;
  wire        queue_next_prk_waked = qvalid_pop[0] ? _queue_next_T_1_prk_waked : _GEN_19;
  wire        _GEN_20 = _GEN_3 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_3_prj_waked =
    _issue_T_2[1] ? queue_2_prj_waked : queue_1_prj_waked;
  wire        queue_next_1_prj_waked =
    qvalid_pop[1] ? _queue_next_T_3_prj_waked : _GEN_20;
  wire        _GEN_21 = _GEN_3 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_3_prk_waked =
    _issue_T_2[1] ? queue_2_prk_waked : queue_1_prk_waked;
  wire        queue_next_1_prk_waked =
    qvalid_pop[1] ? _queue_next_T_3_prk_waked : _GEN_21;
  wire        _GEN_22 = _GEN_6 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_5_prj_waked =
    _issue_T_2[2] ? queue_3_prj_waked : queue_2_prj_waked;
  wire        queue_next_2_prj_waked =
    qvalid_pop[2] ? _queue_next_T_5_prj_waked : _GEN_22;
  wire        _GEN_23 = _GEN_6 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_5_prk_waked =
    _issue_T_2[2] ? queue_3_prk_waked : queue_2_prk_waked;
  wire        queue_next_2_prk_waked =
    qvalid_pop[2] ? _queue_next_T_5_prk_waked : _GEN_23;
  wire        _GEN_24 = _GEN_9 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_7_prj_waked =
    _issue_T_2[3] ? queue_4_prj_waked : queue_3_prj_waked;
  wire        queue_next_3_prj_waked =
    qvalid_pop[3] ? _queue_next_T_7_prj_waked : _GEN_24;
  wire        _GEN_25 = _GEN_9 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_7_prk_waked =
    _issue_T_2[3] ? queue_4_prk_waked : queue_3_prk_waked;
  wire        queue_next_3_prk_waked =
    qvalid_pop[3] ? _queue_next_T_7_prk_waked : _GEN_25;
  wire        _GEN_26 = _GEN_12 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_9_prj_waked =
    _issue_T_2[4] ? queue_5_prj_waked : queue_4_prj_waked;
  wire        queue_next_4_prj_waked =
    qvalid_pop[4] ? _queue_next_T_9_prj_waked : _GEN_26;
  wire        _GEN_27 = _GEN_12 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_9_prk_waked =
    _issue_T_2[4] ? queue_5_prk_waked : queue_4_prk_waked;
  wire        queue_next_4_prk_waked =
    qvalid_pop[4] ? _queue_next_T_9_prk_waked : _GEN_27;
  wire        _GEN_28 = _GEN_15 ? io_prj_ready_1 : io_prj_ready_0;
  wire        queue_next_5_prj_waked = qvalid_pop[5] ? queue_5_prj_waked : _GEN_28;
  wire        _GEN_29 = _GEN_15 ? io_prk_ready_1 : io_prk_ready_0;
  wire        queue_next_5_prk_waked = qvalid_pop[5] ? queue_5_prk_waked : _GEN_29;
  always @(posedge clock) begin
    if (reset) begin
      queue_0_inst_prj <= 6'h0;
      queue_0_inst_prk <= 6'h0;
      queue_0_inst_rd_valid <= 1'h0;
      queue_0_inst_prd <= 6'h0;
      queue_0_inst_imm <= 32'h0;
      queue_0_inst_rob_index <= 5'h0;
      queue_0_inst_alu_op <= 4'h0;
      queue_0_inst_alu_rs1_sel <= 1'h0;
      queue_0_inst_alu_rs2_sel <= 2'h0;
      queue_0_inst_pc <= 32'h0;
      queue_0_prj_waked <= 1'h0;
      queue_0_prk_waked <= 1'h0;
      queue_1_inst_prj <= 6'h0;
      queue_1_inst_prk <= 6'h0;
      queue_1_inst_rd_valid <= 1'h0;
      queue_1_inst_prd <= 6'h0;
      queue_1_inst_imm <= 32'h0;
      queue_1_inst_rob_index <= 5'h0;
      queue_1_inst_alu_op <= 4'h0;
      queue_1_inst_alu_rs1_sel <= 1'h0;
      queue_1_inst_alu_rs2_sel <= 2'h0;
      queue_1_inst_pc <= 32'h0;
      queue_1_prj_waked <= 1'h0;
      queue_1_prk_waked <= 1'h0;
      queue_2_inst_prj <= 6'h0;
      queue_2_inst_prk <= 6'h0;
      queue_2_inst_rd_valid <= 1'h0;
      queue_2_inst_prd <= 6'h0;
      queue_2_inst_imm <= 32'h0;
      queue_2_inst_rob_index <= 5'h0;
      queue_2_inst_alu_op <= 4'h0;
      queue_2_inst_alu_rs1_sel <= 1'h0;
      queue_2_inst_alu_rs2_sel <= 2'h0;
      queue_2_inst_pc <= 32'h0;
      queue_2_prj_waked <= 1'h0;
      queue_2_prk_waked <= 1'h0;
      queue_3_inst_prj <= 6'h0;
      queue_3_inst_prk <= 6'h0;
      queue_3_inst_rd_valid <= 1'h0;
      queue_3_inst_prd <= 6'h0;
      queue_3_inst_imm <= 32'h0;
      queue_3_inst_rob_index <= 5'h0;
      queue_3_inst_alu_op <= 4'h0;
      queue_3_inst_alu_rs1_sel <= 1'h0;
      queue_3_inst_alu_rs2_sel <= 2'h0;
      queue_3_inst_pc <= 32'h0;
      queue_3_prj_waked <= 1'h0;
      queue_3_prk_waked <= 1'h0;
      queue_4_inst_prj <= 6'h0;
      queue_4_inst_prk <= 6'h0;
      queue_4_inst_rd_valid <= 1'h0;
      queue_4_inst_prd <= 6'h0;
      queue_4_inst_imm <= 32'h0;
      queue_4_inst_rob_index <= 5'h0;
      queue_4_inst_alu_op <= 4'h0;
      queue_4_inst_alu_rs1_sel <= 1'h0;
      queue_4_inst_alu_rs2_sel <= 2'h0;
      queue_4_inst_pc <= 32'h0;
      queue_4_prj_waked <= 1'h0;
      queue_4_prk_waked <= 1'h0;
      queue_5_inst_prj <= 6'h0;
      queue_5_inst_prk <= 6'h0;
      queue_5_inst_rd_valid <= 1'h0;
      queue_5_inst_prd <= 6'h0;
      queue_5_inst_imm <= 32'h0;
      queue_5_inst_rob_index <= 5'h0;
      queue_5_inst_alu_op <= 4'h0;
      queue_5_inst_alu_rs1_sel <= 1'h0;
      queue_5_inst_alu_rs2_sel <= 2'h0;
      queue_5_inst_pc <= 32'h0;
      queue_5_prj_waked <= 1'h0;
      queue_5_prk_waked <= 1'h0;
      num <= 4'h0;
      qvalid <= 6'h0;
    end
    else begin
      if (qvalid_pop[0]) begin
        if (_issue_T_2[0]) begin
          queue_0_inst_prj <= queue_1_inst_prj;
          queue_0_inst_prk <= queue_1_inst_prk;
          queue_0_inst_rd_valid <= queue_1_inst_rd_valid;
          queue_0_inst_prd <= queue_1_inst_prd;
          queue_0_inst_imm <= queue_1_inst_imm;
          queue_0_inst_rob_index <= queue_1_inst_rob_index;
          queue_0_inst_alu_op <= queue_1_inst_alu_op;
          queue_0_inst_alu_rs1_sel <= queue_1_inst_alu_rs1_sel;
          queue_0_inst_alu_rs2_sel <= queue_1_inst_alu_rs2_sel;
          queue_0_inst_pc <= queue_1_inst_pc;
        end
      end
      else begin
        queue_0_inst_prj <= _GEN_1;
        queue_0_inst_prk <= _GEN_2;
        queue_0_inst_rd_valid <=
          _GEN_0 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_0_inst_prd <= _GEN_0 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_0_inst_imm <= _GEN_0 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_0_inst_rob_index <=
          _GEN_0 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_0_inst_alu_op <=
          _GEN_0 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_0_inst_alu_rs1_sel <=
          _GEN_0 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_0_inst_alu_rs2_sel <=
          _GEN_0 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_0_inst_pc <= _GEN_0 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_0_prj_waked <=
        queue_next_prj_waked
        | (|{(queue_next_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_0_prk_waked <=
        queue_next_prk_waked
        | (|{(queue_next_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qvalid_pop[1]) begin
        if (_issue_T_2[1]) begin
          queue_1_inst_prj <= queue_2_inst_prj;
          queue_1_inst_prk <= queue_2_inst_prk;
          queue_1_inst_rd_valid <= queue_2_inst_rd_valid;
          queue_1_inst_prd <= queue_2_inst_prd;
          queue_1_inst_imm <= queue_2_inst_imm;
          queue_1_inst_rob_index <= queue_2_inst_rob_index;
          queue_1_inst_alu_op <= queue_2_inst_alu_op;
          queue_1_inst_alu_rs1_sel <= queue_2_inst_alu_rs1_sel;
          queue_1_inst_alu_rs2_sel <= queue_2_inst_alu_rs2_sel;
          queue_1_inst_pc <= queue_2_inst_pc;
        end
      end
      else begin
        queue_1_inst_prj <= _GEN_4;
        queue_1_inst_prk <= _GEN_5;
        queue_1_inst_rd_valid <=
          _GEN_3 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_1_inst_prd <= _GEN_3 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_1_inst_imm <= _GEN_3 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_1_inst_rob_index <=
          _GEN_3 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_1_inst_alu_op <=
          _GEN_3 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_1_inst_alu_rs1_sel <=
          _GEN_3 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_1_inst_alu_rs2_sel <=
          _GEN_3 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_1_inst_pc <= _GEN_3 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_1_prj_waked <=
        queue_next_1_prj_waked
        | (|{(queue_next_1_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_1_prk_waked <=
        queue_next_1_prk_waked
        | (|{(queue_next_1_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qvalid_pop[2]) begin
        if (_issue_T_2[2]) begin
          queue_2_inst_prj <= queue_3_inst_prj;
          queue_2_inst_prk <= queue_3_inst_prk;
          queue_2_inst_rd_valid <= queue_3_inst_rd_valid;
          queue_2_inst_prd <= queue_3_inst_prd;
          queue_2_inst_imm <= queue_3_inst_imm;
          queue_2_inst_rob_index <= queue_3_inst_rob_index;
          queue_2_inst_alu_op <= queue_3_inst_alu_op;
          queue_2_inst_alu_rs1_sel <= queue_3_inst_alu_rs1_sel;
          queue_2_inst_alu_rs2_sel <= queue_3_inst_alu_rs2_sel;
          queue_2_inst_pc <= queue_3_inst_pc;
        end
      end
      else begin
        queue_2_inst_prj <= _GEN_7;
        queue_2_inst_prk <= _GEN_8;
        queue_2_inst_rd_valid <=
          _GEN_6 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_2_inst_prd <= _GEN_6 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_2_inst_imm <= _GEN_6 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_2_inst_rob_index <=
          _GEN_6 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_2_inst_alu_op <=
          _GEN_6 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_2_inst_alu_rs1_sel <=
          _GEN_6 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_2_inst_alu_rs2_sel <=
          _GEN_6 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_2_inst_pc <= _GEN_6 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_2_prj_waked <=
        queue_next_2_prj_waked
        | (|{(queue_next_2_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_2_prk_waked <=
        queue_next_2_prk_waked
        | (|{(queue_next_2_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qvalid_pop[3]) begin
        if (_issue_T_2[3]) begin
          queue_3_inst_prj <= queue_4_inst_prj;
          queue_3_inst_prk <= queue_4_inst_prk;
          queue_3_inst_rd_valid <= queue_4_inst_rd_valid;
          queue_3_inst_prd <= queue_4_inst_prd;
          queue_3_inst_imm <= queue_4_inst_imm;
          queue_3_inst_rob_index <= queue_4_inst_rob_index;
          queue_3_inst_alu_op <= queue_4_inst_alu_op;
          queue_3_inst_alu_rs1_sel <= queue_4_inst_alu_rs1_sel;
          queue_3_inst_alu_rs2_sel <= queue_4_inst_alu_rs2_sel;
          queue_3_inst_pc <= queue_4_inst_pc;
        end
      end
      else begin
        queue_3_inst_prj <= _GEN_10;
        queue_3_inst_prk <= _GEN_11;
        queue_3_inst_rd_valid <=
          _GEN_9 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_3_inst_prd <= _GEN_9 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_3_inst_imm <= _GEN_9 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_3_inst_rob_index <=
          _GEN_9 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_3_inst_alu_op <=
          _GEN_9 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_3_inst_alu_rs1_sel <=
          _GEN_9 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_3_inst_alu_rs2_sel <=
          _GEN_9 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_3_inst_pc <= _GEN_9 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_3_prj_waked <=
        queue_next_3_prj_waked
        | (|{(queue_next_3_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_3_prk_waked <=
        queue_next_3_prk_waked
        | (|{(queue_next_3_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qvalid_pop[4]) begin
        if (_issue_T_2[4]) begin
          queue_4_inst_prj <= queue_5_inst_prj;
          queue_4_inst_prk <= queue_5_inst_prk;
          queue_4_inst_rd_valid <= queue_5_inst_rd_valid;
          queue_4_inst_prd <= queue_5_inst_prd;
          queue_4_inst_imm <= queue_5_inst_imm;
          queue_4_inst_rob_index <= queue_5_inst_rob_index;
          queue_4_inst_alu_op <= queue_5_inst_alu_op;
          queue_4_inst_alu_rs1_sel <= queue_5_inst_alu_rs1_sel;
          queue_4_inst_alu_rs2_sel <= queue_5_inst_alu_rs2_sel;
          queue_4_inst_pc <= queue_5_inst_pc;
        end
      end
      else begin
        queue_4_inst_prj <= _GEN_13;
        queue_4_inst_prk <= _GEN_14;
        queue_4_inst_rd_valid <=
          _GEN_12 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_4_inst_prd <= _GEN_12 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_4_inst_imm <= _GEN_12 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_4_inst_rob_index <=
          _GEN_12 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_4_inst_alu_op <=
          _GEN_12 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_4_inst_alu_rs1_sel <=
          _GEN_12 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_4_inst_alu_rs2_sel <=
          _GEN_12 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_4_inst_pc <= _GEN_12 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_4_prj_waked <=
        queue_next_4_prj_waked
        | (|{(queue_next_4_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_4_prk_waked <=
        queue_next_4_prk_waked
        | (|{(queue_next_4_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qvalid_pop[5]) begin
      end
      else begin
        queue_5_inst_prj <= _GEN_16;
        queue_5_inst_prk <= _GEN_17;
        queue_5_inst_rd_valid <=
          _GEN_15 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_5_inst_prd <= _GEN_15 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_5_inst_imm <= _GEN_15 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_5_inst_rob_index <=
          _GEN_15 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_5_inst_alu_op <=
          _GEN_15 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_5_inst_alu_rs1_sel <=
          _GEN_15 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_5_inst_alu_rs2_sel <=
          _GEN_15 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_5_inst_pc <= _GEN_15 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_5_prj_waked <=
        queue_next_5_prj_waked
        | (|{(queue_next_5_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_5_prk_waked <=
        queue_next_5_prk_waked
        | (|{(queue_next_5_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (io_flush) begin
        num <= 4'h0;
        qvalid <= 6'h0;
      end
      else begin
        if (io_stall | qvalid[4])
          num <= _num_pop_T_2;
        else
          num <= 4'(_num_pop_T_2 + {2'h0, ins_num});
        if (io_stall) begin
          if (|_qvalid_pop_T)
            qvalid <= _qvalid_pop_T_3;
        end
        else if (ins_num == 2'h2)
          qvalid <= {qvalid_pop[3:0], 2'h3};
        else if (ins_num == 2'h1)
          qvalid <= {qvalid_pop[4:0], 1'h1};
        else if (|_qvalid_pop_T)
          qvalid <= _qvalid_pop_T_3;
      end
    end
  end // always @(posedge)
  assign io_insts_issue_0_inst_prj = queue_0_inst_prj;
  assign io_insts_issue_0_inst_prk = queue_0_inst_prk;
  assign io_insts_issue_0_inst_rd_valid = queue_0_inst_rd_valid;
  assign io_insts_issue_0_inst_prd = queue_0_inst_prd;
  assign io_insts_issue_0_inst_imm = queue_0_inst_imm;
  assign io_insts_issue_0_inst_rob_index = queue_0_inst_rob_index;
  assign io_insts_issue_0_inst_alu_op = queue_0_inst_alu_op;
  assign io_insts_issue_0_inst_alu_rs1_sel = queue_0_inst_alu_rs1_sel;
  assign io_insts_issue_0_inst_alu_rs2_sel = queue_0_inst_alu_rs2_sel;
  assign io_insts_issue_0_inst_pc = queue_0_inst_pc;
  assign io_insts_issue_1_inst_prj = queue_1_inst_prj;
  assign io_insts_issue_1_inst_prk = queue_1_inst_prk;
  assign io_insts_issue_1_inst_rd_valid = queue_1_inst_rd_valid;
  assign io_insts_issue_1_inst_prd = queue_1_inst_prd;
  assign io_insts_issue_1_inst_imm = queue_1_inst_imm;
  assign io_insts_issue_1_inst_rob_index = queue_1_inst_rob_index;
  assign io_insts_issue_1_inst_alu_op = queue_1_inst_alu_op;
  assign io_insts_issue_1_inst_alu_rs1_sel = queue_1_inst_alu_rs1_sel;
  assign io_insts_issue_1_inst_alu_rs2_sel = queue_1_inst_alu_rs2_sel;
  assign io_insts_issue_1_inst_pc = queue_1_inst_pc;
  assign io_insts_issue_2_inst_prj = queue_2_inst_prj;
  assign io_insts_issue_2_inst_prk = queue_2_inst_prk;
  assign io_insts_issue_2_inst_rd_valid = queue_2_inst_rd_valid;
  assign io_insts_issue_2_inst_prd = queue_2_inst_prd;
  assign io_insts_issue_2_inst_imm = queue_2_inst_imm;
  assign io_insts_issue_2_inst_rob_index = queue_2_inst_rob_index;
  assign io_insts_issue_2_inst_alu_op = queue_2_inst_alu_op;
  assign io_insts_issue_2_inst_alu_rs1_sel = queue_2_inst_alu_rs1_sel;
  assign io_insts_issue_2_inst_alu_rs2_sel = queue_2_inst_alu_rs2_sel;
  assign io_insts_issue_2_inst_pc = queue_2_inst_pc;
  assign io_insts_issue_3_inst_prj = queue_3_inst_prj;
  assign io_insts_issue_3_inst_prk = queue_3_inst_prk;
  assign io_insts_issue_3_inst_rd_valid = queue_3_inst_rd_valid;
  assign io_insts_issue_3_inst_prd = queue_3_inst_prd;
  assign io_insts_issue_3_inst_imm = queue_3_inst_imm;
  assign io_insts_issue_3_inst_rob_index = queue_3_inst_rob_index;
  assign io_insts_issue_3_inst_alu_op = queue_3_inst_alu_op;
  assign io_insts_issue_3_inst_alu_rs1_sel = queue_3_inst_alu_rs1_sel;
  assign io_insts_issue_3_inst_alu_rs2_sel = queue_3_inst_alu_rs2_sel;
  assign io_insts_issue_3_inst_pc = queue_3_inst_pc;
  assign io_insts_issue_4_inst_prj = queue_4_inst_prj;
  assign io_insts_issue_4_inst_prk = queue_4_inst_prk;
  assign io_insts_issue_4_inst_rd_valid = queue_4_inst_rd_valid;
  assign io_insts_issue_4_inst_prd = queue_4_inst_prd;
  assign io_insts_issue_4_inst_imm = queue_4_inst_imm;
  assign io_insts_issue_4_inst_rob_index = queue_4_inst_rob_index;
  assign io_insts_issue_4_inst_alu_op = queue_4_inst_alu_op;
  assign io_insts_issue_4_inst_alu_rs1_sel = queue_4_inst_alu_rs1_sel;
  assign io_insts_issue_4_inst_alu_rs2_sel = queue_4_inst_alu_rs2_sel;
  assign io_insts_issue_4_inst_pc = queue_4_inst_pc;
  assign io_insts_issue_5_inst_prj = queue_5_inst_prj;
  assign io_insts_issue_5_inst_prk = queue_5_inst_prk;
  assign io_insts_issue_5_inst_rd_valid = queue_5_inst_rd_valid;
  assign io_insts_issue_5_inst_prd = queue_5_inst_prd;
  assign io_insts_issue_5_inst_imm = queue_5_inst_imm;
  assign io_insts_issue_5_inst_rob_index = queue_5_inst_rob_index;
  assign io_insts_issue_5_inst_alu_op = queue_5_inst_alu_op;
  assign io_insts_issue_5_inst_alu_rs1_sel = queue_5_inst_alu_rs1_sel;
  assign io_insts_issue_5_inst_alu_rs2_sel = queue_5_inst_alu_rs2_sel;
  assign io_insts_issue_5_inst_pc = queue_5_inst_pc;
  assign io_issue_req_0 = qvalid[0] & queue_0_prj_waked & queue_0_prk_waked;
  assign io_issue_req_1 = qvalid[1] & queue_1_prj_waked & queue_1_prk_waked;
  assign io_issue_req_2 = qvalid[2] & queue_2_prj_waked & queue_2_prk_waked;
  assign io_issue_req_3 = qvalid[3] & queue_3_prj_waked & queue_3_prk_waked;
  assign io_issue_req_4 = qvalid[4] & queue_4_prj_waked & queue_4_prk_waked;
  assign io_issue_req_5 = qvalid[5] & queue_5_prj_waked & queue_5_prk_waked;
  assign io_elem_num = num;
  assign io_full = qvalid[4];
endmodule

