// Generated by CIRCT firtool-1.62.0
module Fetch_Queue(
  input         clock,
                reset,
  input  [31:0] io_insts_pack_0_pc,
                io_insts_pack_0_inst,
  input         io_insts_pack_0_inst_valid,
                io_insts_pack_0_predict_jump,
  input  [31:0] io_insts_pack_0_pred_npc,
  input  [7:0]  io_insts_pack_0_exception,
  input  [31:0] io_insts_pack_1_pc,
                io_insts_pack_1_inst,
  input         io_insts_pack_1_inst_valid,
                io_insts_pack_1_predict_jump,
  input  [31:0] io_insts_pack_1_pred_npc,
  input  [7:0]  io_insts_pack_1_exception,
  input         io_next_ready,
                io_flush,
  output        io_insts_valid_decode_0,
                io_insts_valid_decode_1,
  output [31:0] io_insts_pack_id_0_pc,
                io_insts_pack_id_0_inst,
  output        io_insts_pack_id_0_predict_jump,
  output [31:0] io_insts_pack_id_0_pred_npc,
  output [7:0]  io_insts_pack_id_0_exception,
  output [31:0] io_insts_pack_id_1_pc,
                io_insts_pack_id_1_inst,
  output        io_insts_pack_id_1_predict_jump,
  output [31:0] io_insts_pack_id_1_pred_npc,
  output [7:0]  io_insts_pack_id_1_exception,
  output        io_full
);

  reg  [31:0] queue_0_0_pc;
  reg  [31:0] queue_0_0_inst;
  reg         queue_0_0_predict_jump;
  reg  [31:0] queue_0_0_pred_npc;
  reg  [7:0]  queue_0_0_exception;
  reg  [31:0] queue_0_1_pc;
  reg  [31:0] queue_0_1_inst;
  reg         queue_0_1_predict_jump;
  reg  [31:0] queue_0_1_pred_npc;
  reg  [7:0]  queue_0_1_exception;
  reg  [31:0] queue_0_2_pc;
  reg  [31:0] queue_0_2_inst;
  reg         queue_0_2_predict_jump;
  reg  [31:0] queue_0_2_pred_npc;
  reg  [7:0]  queue_0_2_exception;
  reg  [31:0] queue_0_3_pc;
  reg  [31:0] queue_0_3_inst;
  reg         queue_0_3_predict_jump;
  reg  [31:0] queue_0_3_pred_npc;
  reg  [7:0]  queue_0_3_exception;
  reg  [31:0] queue_1_0_pc;
  reg  [31:0] queue_1_0_inst;
  reg         queue_1_0_predict_jump;
  reg  [31:0] queue_1_0_pred_npc;
  reg  [7:0]  queue_1_0_exception;
  reg  [31:0] queue_1_1_pc;
  reg  [31:0] queue_1_1_inst;
  reg         queue_1_1_predict_jump;
  reg  [31:0] queue_1_1_pred_npc;
  reg  [7:0]  queue_1_1_exception;
  reg  [31:0] queue_1_2_pc;
  reg  [31:0] queue_1_2_inst;
  reg         queue_1_2_predict_jump;
  reg  [31:0] queue_1_2_pred_npc;
  reg  [7:0]  queue_1_2_exception;
  reg  [31:0] queue_1_3_pc;
  reg  [31:0] queue_1_3_inst;
  reg         queue_1_3_predict_jump;
  reg  [31:0] queue_1_3_pred_npc;
  reg  [7:0]  queue_1_3_exception;
  reg  [7:0]  mask;
  wire [3:0]  mask_0 = {mask[6], mask[4], mask[2], mask[0]};
  reg  [3:0]  head;
  wire [3:0]  rear = mask_0 | {mask[7], mask[5], mask[3], mask[1]};
  wire [3:0]  _full_T_3 = head & {rear[2:0], rear[3]};
  wire        io_insts_valid_decode_1_0 = (head & rear) == 4'h0;
  wire [7:0]  _io_insts_pack_id_0_T_4 = head[0] ? queue_0_0_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_0_T_5 = head[1] ? queue_0_1_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_0_T_6 = head[2] ? queue_0_2_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_0_T_7 = head[3] ? queue_0_3_exception : 8'h0;
  wire [31:0] _io_insts_pack_id_0_T_11 = head[0] ? queue_0_0_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_12 = head[1] ? queue_0_1_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_13 = head[2] ? queue_0_2_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_14 = head[3] ? queue_0_3_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_32 = head[0] ? queue_0_0_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_33 = head[1] ? queue_0_1_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_34 = head[2] ? queue_0_2_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_35 = head[3] ? queue_0_3_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_39 = head[0] ? queue_0_0_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_40 = head[1] ? queue_0_1_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_41 = head[2] ? queue_0_2_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_42 = head[3] ? queue_0_3_pc : 32'h0;
  wire [7:0]  _io_insts_pack_id_1_T_4 = head[0] ? queue_1_0_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_1_T_5 = head[1] ? queue_1_1_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_1_T_6 = head[2] ? queue_1_2_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_1_T_7 = head[3] ? queue_1_3_exception : 8'h0;
  wire [31:0] _io_insts_pack_id_1_T_11 = head[0] ? queue_1_0_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_12 = head[1] ? queue_1_1_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_13 = head[2] ? queue_1_2_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_14 = head[3] ? queue_1_3_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_32 = head[0] ? queue_1_0_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_33 = head[1] ? queue_1_1_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_34 = head[2] ? queue_1_2_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_35 = head[3] ? queue_1_3_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_39 = head[0] ? queue_1_0_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_40 = head[1] ? queue_1_1_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_41 = head[2] ? queue_1_2_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_42 = head[3] ? queue_1_3_pc : 32'h0;
  wire        _queue_0_0_T_1 = mask_0 == 4'h0;
  wire        _queue_0_1_T_1 = mask_0 == 4'h0;
  wire        _queue_0_2_T_1 = mask_0 == 4'h0;
  wire        _queue_0_3_T_1 = mask_0 == 4'h0;
  wire [7:0]  enqueue_mask =
    mask & {8{io_insts_pack_0_inst_valid}} | {mask[6:0], mask[7]}
    & {8{io_insts_pack_1_inst_valid}};
  always @(posedge clock) begin
    if (reset) begin
      queue_0_0_pc <= 32'h0;
      queue_0_0_inst <= 32'h0;
      queue_0_0_predict_jump <= 1'h0;
      queue_0_0_pred_npc <= 32'h0;
      queue_0_0_exception <= 8'h0;
      queue_0_1_pc <= 32'h0;
      queue_0_1_inst <= 32'h0;
      queue_0_1_predict_jump <= 1'h0;
      queue_0_1_pred_npc <= 32'h0;
      queue_0_1_exception <= 8'h0;
      queue_0_2_pc <= 32'h0;
      queue_0_2_inst <= 32'h0;
      queue_0_2_predict_jump <= 1'h0;
      queue_0_2_pred_npc <= 32'h0;
      queue_0_2_exception <= 8'h0;
      queue_0_3_pc <= 32'h0;
      queue_0_3_inst <= 32'h0;
      queue_0_3_predict_jump <= 1'h0;
      queue_0_3_pred_npc <= 32'h0;
      queue_0_3_exception <= 8'h0;
      queue_1_0_pc <= 32'h0;
      queue_1_0_inst <= 32'h0;
      queue_1_0_predict_jump <= 1'h0;
      queue_1_0_pred_npc <= 32'h0;
      queue_1_0_exception <= 8'h0;
      queue_1_1_pc <= 32'h0;
      queue_1_1_inst <= 32'h0;
      queue_1_1_predict_jump <= 1'h0;
      queue_1_1_pred_npc <= 32'h0;
      queue_1_1_exception <= 8'h0;
      queue_1_2_pc <= 32'h0;
      queue_1_2_inst <= 32'h0;
      queue_1_2_predict_jump <= 1'h0;
      queue_1_2_pred_npc <= 32'h0;
      queue_1_2_exception <= 8'h0;
      queue_1_3_pc <= 32'h0;
      queue_1_3_inst <= 32'h0;
      queue_1_3_predict_jump <= 1'h0;
      queue_1_3_pred_npc <= 32'h0;
      queue_1_3_exception <= 8'h0;
      mask <= 8'h1;
      head <= 4'h1;
    end
    else begin
      if (~(|_full_T_3) & enqueue_mask[0]) begin
        queue_0_0_pc <= _queue_0_0_T_1 ? io_insts_pack_1_pc : io_insts_pack_0_pc;
        queue_0_0_inst <= _queue_0_0_T_1 ? io_insts_pack_1_inst : io_insts_pack_0_inst;
        queue_0_0_predict_jump <=
          _queue_0_0_T_1 ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
        queue_0_0_pred_npc <=
          _queue_0_0_T_1 ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
        queue_0_0_exception <=
          _queue_0_0_T_1 ? io_insts_pack_1_exception : io_insts_pack_0_exception;
      end
      if (~(|_full_T_3) & enqueue_mask[2]) begin
        queue_0_1_pc <= _queue_0_1_T_1 ? io_insts_pack_1_pc : io_insts_pack_0_pc;
        queue_0_1_inst <= _queue_0_1_T_1 ? io_insts_pack_1_inst : io_insts_pack_0_inst;
        queue_0_1_predict_jump <=
          _queue_0_1_T_1 ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
        queue_0_1_pred_npc <=
          _queue_0_1_T_1 ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
        queue_0_1_exception <=
          _queue_0_1_T_1 ? io_insts_pack_1_exception : io_insts_pack_0_exception;
      end
      if (~(|_full_T_3) & enqueue_mask[4]) begin
        queue_0_2_pc <= _queue_0_2_T_1 ? io_insts_pack_1_pc : io_insts_pack_0_pc;
        queue_0_2_inst <= _queue_0_2_T_1 ? io_insts_pack_1_inst : io_insts_pack_0_inst;
        queue_0_2_predict_jump <=
          _queue_0_2_T_1 ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
        queue_0_2_pred_npc <=
          _queue_0_2_T_1 ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
        queue_0_2_exception <=
          _queue_0_2_T_1 ? io_insts_pack_1_exception : io_insts_pack_0_exception;
      end
      if (~(|_full_T_3) & enqueue_mask[6]) begin
        queue_0_3_pc <= _queue_0_3_T_1 ? io_insts_pack_1_pc : io_insts_pack_0_pc;
        queue_0_3_inst <= _queue_0_3_T_1 ? io_insts_pack_1_inst : io_insts_pack_0_inst;
        queue_0_3_predict_jump <=
          _queue_0_3_T_1 ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
        queue_0_3_pred_npc <=
          _queue_0_3_T_1 ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
        queue_0_3_exception <=
          _queue_0_3_T_1 ? io_insts_pack_1_exception : io_insts_pack_0_exception;
      end
      if (~(|_full_T_3) & enqueue_mask[1]) begin
        queue_1_0_pc <= (|mask_0) ? io_insts_pack_1_pc : io_insts_pack_0_pc;
        queue_1_0_inst <= (|mask_0) ? io_insts_pack_1_inst : io_insts_pack_0_inst;
        queue_1_0_predict_jump <=
          (|mask_0) ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
        queue_1_0_pred_npc <=
          (|mask_0) ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
        queue_1_0_exception <=
          (|mask_0) ? io_insts_pack_1_exception : io_insts_pack_0_exception;
      end
      if (~(|_full_T_3) & enqueue_mask[3]) begin
        queue_1_1_pc <= (|mask_0) ? io_insts_pack_1_pc : io_insts_pack_0_pc;
        queue_1_1_inst <= (|mask_0) ? io_insts_pack_1_inst : io_insts_pack_0_inst;
        queue_1_1_predict_jump <=
          (|mask_0) ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
        queue_1_1_pred_npc <=
          (|mask_0) ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
        queue_1_1_exception <=
          (|mask_0) ? io_insts_pack_1_exception : io_insts_pack_0_exception;
      end
      if (~(|_full_T_3) & enqueue_mask[5]) begin
        queue_1_2_pc <= (|mask_0) ? io_insts_pack_1_pc : io_insts_pack_0_pc;
        queue_1_2_inst <= (|mask_0) ? io_insts_pack_1_inst : io_insts_pack_0_inst;
        queue_1_2_predict_jump <=
          (|mask_0) ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
        queue_1_2_pred_npc <=
          (|mask_0) ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
        queue_1_2_exception <=
          (|mask_0) ? io_insts_pack_1_exception : io_insts_pack_0_exception;
      end
      if (~(|_full_T_3) & enqueue_mask[7]) begin
        queue_1_3_pc <= (|mask_0) ? io_insts_pack_1_pc : io_insts_pack_0_pc;
        queue_1_3_inst <= (|mask_0) ? io_insts_pack_1_inst : io_insts_pack_0_inst;
        queue_1_3_predict_jump <=
          (|mask_0) ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
        queue_1_3_pred_npc <=
          (|mask_0) ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
        queue_1_3_exception <=
          (|mask_0) ? io_insts_pack_1_exception : io_insts_pack_0_exception;
      end
      if (io_flush) begin
        mask <= 8'h1;
        head <= 4'h1;
      end
      else begin
        if (~(|_full_T_3) & io_insts_pack_0_inst_valid) begin
          if (io_insts_pack_1_inst_valid)
            mask <= {mask[5:0], mask[7:6]};
          else
            mask <= {mask[6:0], mask[7]};
        end
        if (io_next_ready & io_insts_valid_decode_1_0)
          head <= {head[2:0], head[3]};
      end
    end
  end // always @(posedge)
  assign io_insts_valid_decode_0 = io_insts_valid_decode_1_0;
  assign io_insts_valid_decode_1 = io_insts_valid_decode_1_0;
  assign io_insts_pack_id_0_pc =
    _io_insts_pack_id_0_T_39 | _io_insts_pack_id_0_T_40 | _io_insts_pack_id_0_T_41
    | _io_insts_pack_id_0_T_42;
  assign io_insts_pack_id_0_inst =
    _io_insts_pack_id_0_T_32 | _io_insts_pack_id_0_T_33 | _io_insts_pack_id_0_T_34
    | _io_insts_pack_id_0_T_35;
  assign io_insts_pack_id_0_predict_jump =
    head[0] & queue_0_0_predict_jump | head[1] & queue_0_1_predict_jump | head[2]
    & queue_0_2_predict_jump | head[3] & queue_0_3_predict_jump;
  assign io_insts_pack_id_0_pred_npc =
    _io_insts_pack_id_0_T_11 | _io_insts_pack_id_0_T_12 | _io_insts_pack_id_0_T_13
    | _io_insts_pack_id_0_T_14;
  assign io_insts_pack_id_0_exception =
    _io_insts_pack_id_0_T_4 | _io_insts_pack_id_0_T_5 | _io_insts_pack_id_0_T_6
    | _io_insts_pack_id_0_T_7;
  assign io_insts_pack_id_1_pc =
    _io_insts_pack_id_1_T_39 | _io_insts_pack_id_1_T_40 | _io_insts_pack_id_1_T_41
    | _io_insts_pack_id_1_T_42;
  assign io_insts_pack_id_1_inst =
    _io_insts_pack_id_1_T_32 | _io_insts_pack_id_1_T_33 | _io_insts_pack_id_1_T_34
    | _io_insts_pack_id_1_T_35;
  assign io_insts_pack_id_1_predict_jump =
    head[0] & queue_1_0_predict_jump | head[1] & queue_1_1_predict_jump | head[2]
    & queue_1_2_predict_jump | head[3] & queue_1_3_predict_jump;
  assign io_insts_pack_id_1_pred_npc =
    _io_insts_pack_id_1_T_11 | _io_insts_pack_id_1_T_12 | _io_insts_pack_id_1_T_13
    | _io_insts_pack_id_1_T_14;
  assign io_insts_pack_id_1_exception =
    _io_insts_pack_id_1_T_4 | _io_insts_pack_id_1_T_5 | _io_insts_pack_id_1_T_6
    | _io_insts_pack_id_1_T_7;
  assign io_full = |_full_T_3;
endmodule

